name = "Vavilov1991"
version = "0.1.0"
defaultTargets = ["Vavilov1991"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "a218e50f981942cba4fd060faff7cae680805062"

[[lean_lib]]
name = "Vavilov1991"
