#import "main-defs.typ": *
#import "diagrams/chapter1-double.typ": double-square, relative-square

== Relative groups and unipotents <sec:relative-groups>

Here we introduce the congruence subgroups of the Chevalley groups and the
relative elementary groups which are necessary to formulate the structure
theorems. Also we describe informally the distinction between unipotent root
elements and unipotent elements of root type.

=== Unipotent root elements <ss:unipotent-root-elements>

In what follows we consider several generalizations of the elementary root
unipotents $x_alpha (xi)$. Some of these generalizations are defined entirely in
terms of the Chevalley group $G$ itself and some depend on a particular choice
of representation.

The first of these generalizations is quite familiar. Let us recall that $x$ is
called a _(unipotent) root element_ if it is conjugate in $G$ to $x_alpha (xi)$
for some $alpha in Phi$ and some $xi in R$. It is called a _long root element_
if $alpha$ is long and a _short root element_ if $alpha$ is short. Let $I$ be an
ideal in $R$. If $xi in I$ we say that $x$ has level $I$ (classically one would
say that the level of $x$ is contained in $I$).

The normal subgroup of the elementary group $E=E(Phi,R)$ generated by all the
elementary root unipotents of level $I$ (i.e. the smallest normal subgroup of
$E$ which contains all of these elements) is called the _elementary subgroup of
level_ $I$ and is denoted by $E_I=E(Phi,R,I)$:
$ E(Phi,R,I)=⟨x_alpha (xi),alpha in Phi,xi in I⟩^(E(Phi,R)). $
When $I != R$ we refer to $E_I$ as a _relative elementary subgroup_ as
contrasted to the absolute one. For a given $I$ the group $E_I$ actually does
depend on a particular choice of $R$.#ed-note[Distinguish this normal closure
  from the subgroup $E(Phi,I)$ generated by the same root elements without
  taking conjugates. The splitting principle and its consequences are developed
  in #citation[@bib:Stepanov2014, §1.12]\; relative normality and commutator
  formulas are discussed in #citation[@bib:Stepanov2014, §2.6].]

It is not true in general that $E_I$ is generated by its elementary root
unipotents. However the Chevalley commutator formula implies that, for
irreducible $Phi$ of rank at least 2, $E_I$ is generated by the elements of the
form $x_alpha (xi)x_(-alpha)(zeta)x_alpha (-xi)$, $alpha in Phi$, $xi in R$,
$zeta in I$ (see for example #citation[@bib:Vaserstein1976, @bib:Tits1976,
  @bib:Abe1983, @bib:Vaserstein1986b, @bib:Vavilov1988e]). In particular this
shows that $E_I$ is generated by all of its root unipotents obtained by
elementary conjugation.

Actually with a bit of extra work one can even show that $E_I$ is generated
#source(246)
by its long root unipotents, see #citation[@bib:Vavilov1988e]. It suffices to
show that any elementary short root unipotent $x_beta (xi)$ is a product of long
root unipotents $x_1,dots,x_m$ from $E(Phi,R,I)$ (not necessarily elementary any
more). In fact then for any $z in E(Phi,R)$ one concludes that
$z x_beta (xi) z^(-1)=(z x_1 z^(-1)) dots.c (z x_m z^(-1))$ is also a product of
long root unipotents. Now if $Phi != G_2$ then there exists a long root $alpha$
and a short root $gamma$ such that $beta=alpha+gamma$. Then the root
$alpha+2gamma=beta+gamma$ is long and the Chevalley formula implies that
$
  x_beta (±xi)=x_alpha (xi)
  (x_gamma (1)x_alpha (-xi)x_gamma (-1))x_(beta+gamma)(±xi),
$
where the right hand side is a product of long root unipotents from
$E(Phi,R,I)$; the signs depend on the chosen root vectors. For the case
$Phi=G_2$ the proof is somewhat more tricky since direct use of the Chevalley
commutator formula provides the result only under the additional assumption
$2I=I$.

Now normality of $E_I$ in the Chevalley group $G$ amounts to the fact that _any_
root unipotent of level $I$ is contained in $E_I$. When the preceding long-root
generation applies, it is enough to check long root unipotents.

=== Congruence subgroups <ss:congruence-subgroups>

Let again $I$ be an ideal in $R$. Then $I$ defines the corresponding
_reduction homomorphism_
$ phi_I:G(Phi,R) -> G(Phi,R/I), $
see #citation[@bib:Abe1969, @bib:Stein1971a, @bib:Stein1971b]. If we look at the
group $G=G(Phi,R)$ in a particular representation $pi$ then $phi_I$ is very easy
to describe: one has just to reduce every entry of a matrix representing an
element $g in G$ modulo $I$, i.e. take
$overline(g)_(lambda mu)=phi_I (g_(lambda mu))=g_(lambda mu)+I$. The kernel of
$phi_I$ is denoted by $G_I=G(Phi,R,I)$ and is called the _principal congruence
subgroup of level_ $I$. By the definition $G_I$ is a normal subgroup of $G$ and
one has the following exact sequence:
$ 1 -> G(Phi,R,I) -> G(Phi,R) -> Im(phi_I) -> 1. $
Reduction need not be surjective onto all of $G(Phi,R/I)$.

Similarly the inverse image under $phi_I$ of the centre of $G(Phi,R/I)$ is
denoted by $C_I=C(Phi,R,I)$ (sometimes by $G'_I=G'(Phi,R,I)$) and is called the
_full congruence subgroup of level_ $I$. To stress that $G(Phi,R,I)$ and
$C(Phi,R,I)$ are considered in a particular representation we write
$G_pi (Phi, R, I)$ and $C_pi (Phi, R, I)$ respectively. For a fixed group scheme
the principal subgroup is the kernel of its reduction map; passing to the image
in a representation with a central kernel can change that kernel. The full
congruence subgroup also depends on the chosen form of the group and its centre.

Clearly one has $E_I ≤ G_I ≤ C_I$. In §@sec:structure-theorems we discuss the
_standard description of the normal subgroups_ in $G$ which says that (with some
minor restrictions on $Phi$ and $R$) all of them lie between $E_I$ and $C_I$ for
some (uniquely determined) ideal $I$ of $R$. In fact for most of the excluded
cases E.~Abe could
#source(247)
recover a _parastandard description_ of normal subgroups in terms of generalized
congruence subgroups #citation[@bib:Abe1969, @bib:Abe1976, @bib:Abe1989a,
  @bib:Abe1989b] but we cannot reproduce their definition here.

When the standard description holds the classification of normal subgroups in
$G$ is reduced to the computation of factor-groups $C_I/E_I$ or, since the
structure of $C_I/G_I$ is clear, to the computation of the
_relative $K_1$-functors_
$ K_1(Phi,R,I)=G(Phi,R,I)/E(Phi,R,I). $
Of course this last problem is highly non-trivial and was solved only for some
very special classes of rings.

=== Relativization <ss:relativization>

There is a very simple general trick which usually allows us to reduce problems
about relative groups to those for the absolute ones. It goes back to the works
of R.~Swan and M.~R.~Stein #citation[@bib:Stein1971a] and was first applied to
the normality problem by A.~A.~Suslin and V.~I.~Kopeiko
#citation[@bib:Suslin1982] and used later by L.~N.~Vaserstein
#citation[@bib:Vaserstein1981, proof of Theorem 13] for general linear groups,
and for Chevalley groups #citation[@bib:Vaserstein1986b, §2, p. 221]. Although
our new approach does not distinguish the relative and absolute cases we find it
very instructive to show this idea here.

Define the _double_ $D=R times_I R$ of a ring $R$ with respect to an ideal
$I ⊆ R$ by the Cartesian square:

#align(center)[#diagram(double-square())]

In other words $D$ consists of all the pairs $(a,b) in R times R$ such that
$a ≡ b (mod I)$ with the component-wise operations and $pi_1(a,b)=a$,
$pi_2(a,b)=b$. Clearly $Ker pi_1=(0,I)$ and $Ker pi_2=(I,0)$. The diagonal
embedding $delta:R -> D$ given by $delta(a)=(a,a)$ splits both $pi_1$ and
$pi_2$. In fact $D$ is the semidirect product of $delta(R) ≅ R$ and
$Ker pi_1 ≅ I$. This means that $D$ is isomorphic to the set of pairs $(a,c)$,
$a in R$, $c in I$, with the component-wise addition and the multiplication
given by $(a,c)(b,d)=(a b,a d+c b+c d)$. The isomorphism sends $(a,c)$ to
$(a,a+c)$. In the sequel we identify $I$ with $Ker pi_1$.

Now Stein has proven that the relative groups defined in terms of the following
split exact sequences coincide with the usual ones:
#source(248)
$ 1 -> E(Phi,R,I) -> E(Phi,D) arrow.r^(pi_1) E(Phi,R) -> 1, $
$ 1 -> G(Phi,R,I) -> G(Phi,D) arrow.r^(pi_1) G(Phi,R) -> 1. $
Both sequences have section induced by $delta$. For the elementary groups one
has $E(Phi,D,I) ≅ E(Phi,R,I)$, the isomorphism induced by $pi_2$, and the
following commutative diagram:

#align(center)[#diagram(relative-square())]

The upper horizontal map is split surjective. Elementary reduction need not have
the expected relative kernel at $E(Phi,R)$: the kernel of elementary reduction
can exceed $E(Phi,R,I)$. The natural embeddings $E(Phi,R,I) -> E(Phi,R)$ and
$G(Phi,R,I) -> G(Phi,R)$ are defined by $pi_2$. But now we are in a much better
position because the new exact sequences split.

The splitting principle gives
$ G(Phi,D,I) ∩ E(Phi,D)=E(Phi,D,I) $
(see #citation[@bib:Suslin1981b, @bib:Vaserstein1986b] for details). If the
absolute elementary groups are normal in the corresponding Chevalley groups for
all commutative rings, then $E(Phi,D,I)$ is an intersection of two normal
subgroups of $G(Phi,D)$. Its image under the surjective map induced by $pi_2$ is
$E(Phi,R,I)$, which is therefore normal in $G(Phi,R)$.#ed-note[For a systematic
  treatment of the splitting principle see #citation[@bib:Stepanov2014, §1.12].
  The double is a pullback of rings; the split projection makes the
  relative-to-absolute reduction work without assuming that every point lifts
  modulo $I$.]

=== Unipotent elements of root type <ss:unipotent-root-type>

Unfortunately the root elements introduced above are not sufficient for our
purposes. Actually to prove that a root unipotent lies in $E_I$ we will write it
as a product of factors which are not root unipotents themselves—though have
formal properties very similar to those of root unipotents.

Let us look at the matrix representing a root unipotent $x$ in a minimal
representation $pi$. Over a field its residue $m=op("res")(x)$ is small with
respect to the dimension $n=dim(pi)$ and we may write $x$ in the form
$x=e+u_1 v_1+dots+u_m v_m$, where $u_1,dots,u_m$ are columns of height $n$
(elements of the module $V$) while $v_1,dots,v_m$ are rows of length $n$
(elements of the dual module $V^*$). Over a ring we use explicitly given
column–row expressions rather than assuming that rank alone provides such a
factorization. Now for any root unipotent the
#source(249)
resulting columns and rows satisfy some equations. A typical example of such an
equation is, of course, $v_i u_i=0$. Another typical example is when the module
$V ≅ V^*$ bears an orthogonal/symplectic structure and $v_i=tilde(u)_(m+1-i)$
for a given isomorphism $u |-> tilde(u)$ of $V$ and $V^*$. In turn these
equations on $u_1,dots,u_m$ and $v_1,dots,v_m$ guarantee that the matrix
$x=e+u_1 v_1+dots+u_m v_m$ does actually belong to the Chevalley group
$G_pi (Phi, R)$. We refer to the resulting class of matrices as the _(unipotent)
elements of root type_. The resulting class of elements depends a priori on the
choice of $pi$ and to stress this we sometimes say “elements of root type in the
representation $pi$”. The precise defining equations will be specified for each
representation; this phrase alone is not a definition independent of those
equations.

If all the coordinates of $u_1,dots,u_m$ or $v_1,dots,v_m$ belong to an ideal
$I$ of $R$ then we refer to $x$ as an element of level $I$. Clearly in this case
$x$ belongs to the principal congruence subgroup $G_pi (Phi, R, I)$. In most
cases one has to look only at those elements for which the coordinates have a
common factor belonging to $I$. In other words one may think that $u_1,dots,u_m$
and $v_1,dots,v_m$ are arbitrary columns and rows subject to the equations but
consider $x(xi)=e+u_1 xi v_1+dots+u_m xi v_m$, $xi in I$, rather than $x$,
whenever the defining equations are preserved by this parameterization.

=== Geometry of root subgroups <ss:geometry-root-subgroups>

If $R=K$ is a field the classes of unipotent root elements and unipotent
elements of root type coincide in the representations considered below. This is
not the case for an arbitrary ring $R$. For most of our considerations we use
only some very special elements of root type. Actually almost all of our needs
are covered by what we call _fake root unipotents_, i.e. those elements of root
type which are conjugated to an element of $U=U(Phi,R)$. Obviously a root
unipotent is also a fake root unipotent. Over general rings the converse can
fail; the relation over Bézout rings (rings in which every finitely generated
ideal is principal) will be discussed in the concrete representations. The class
of fake root unipotents may also be characterized in internal terms. Later we
describe in some details the situation for the classical examples and the case
$Phi=E_6$.

The information necessary to check that an element $z$ from $U$ is an element of
root type is available at the level of fields. Let $K$ be a field. Write $z$ as
a product of $x_beta (z_beta)$, $z_beta in K$, over all positive roots
$beta in Phi^+$ in a fixed order. If we want the element $z in U$ to be
conjugated to an elementary unipotent $x_alpha (xi)$ its coefficients $z_beta$
have to satisfy some polynomial equations. They are particularly easy when $z$
has very few non-zero coefficients and are readily expressed in terms of
geometry of root subgroups (see #citation[@bib:Cooperstein1979,
  @bib:Cooperstein1981, @bib:Vavilov1988d] for further references).

#source(250)
A typical result here is that for a field any pair of long root subgroups $X,Y$
in $G=G(Phi,K)$ is simultaneously conjugated to a pair of elementary root
subgroups $X_alpha,X_beta$ where $alpha$ and $beta$ are long roots, i.e. there
exists such a $g in G$ that $g X g^(-1)=X_alpha$ and $g Y g^(-1)=X_beta$. This
means that we may speak about the _angle_ between the root subgroups $X$ and $Y$
which takes one of the following values: $0,pi/3,pi/2,2pi/3,pi$. The geometry of
short root subgroups is much more cumbersome since they may correspond not only
to short roots but to certain pairs of long roots (see
#citation[@bib:Vavilov1989]).

Let us give two patterns which cover most of our needs. If $X_1,dots,X_m$ are
long root subgroups every pair of which forms the angle $pi/3$ (in the
Cooperstein’s terminology they generate a “singular subspace” of dimension
$≤ m-1$) then any element $x in X_1 dots.c X_m$ from their product is a long
root unipotent. This means that even over a ring absolutely any element of the
corresponding product is an element of long root type.

Another archetypal configuration is when each of the root subgroups
$X_1,dots,X_m$ forms the angle $pi/3$ with all the others but one and is
orthogonal to that one. In that case the long root elements form a quadric in
$X_1 dots.c X_m$. A necessary condition for an element $x in X_1 dots.c X_m$ to
be a long root element is that its components in each of the groups
$X_1,dots,X_m$ satisfy a certain quadratic equation (which is as we shall see
closely related to the equations defining the orbit of the highest weight
vector). But then an element of the corresponding product over a ring satisfying
the equation will be a long root type element.

These two configurations correspond to the Dynkin diagrams (or rather Carter
graphs #citation[@bib:Carter1972a]) of types $A_m$ and $D_(m/2)$ respectively.
We encounter some more sophisticated patterns when there are two different root
lengths.
