#import "main-defs.typ": *
#import "diagrams/classical-weights.typ": type-a, type-b, type-c, type-d, type-g
#let sdiag = math.op("sdiag")
#let Epin = group-name("Epin")
#let PSp = group-name("PSp")
#let PSO = group-name("PSO")
#let Isom = group-name("Isom")
#let KO = group-name("KO")
#source(251)

== The classical cases <sec:classical-cases>

Here we recall the familiar identifications for the Chevalley groups of
classical types and the corresponding minimal modules and illustrate some of the
notions introduced before on these examples.

=== The case $Phi = A_ell$ <ss:type-a>

Here the group $G_("sc")(A_ell,R)$ is isomorphic to the _special linear group_
$SL(ell+1, R)$ of degree $ell+1$ over $R$, and the adjoint group scheme is the
_projective general linear group_ $PGL_(ell+1)$.#ed-note[The central isogeny
  $SL_(ell+1) -> PGL_(ell+1)$ need not be surjective on $R$-points. The adjoint
  group's $R$-points therefore need not equal $SL(ell+1, R)$ modulo scalar
  matrices.] In turn $E_("sc")(Phi,R)=E(ell+1,R)$ is the _elementary group_, the
group generated by all _elementary transvections_ $t_(i j)(xi)=e+xi e_(i j)$,
$xi in R$, $i != j$. Here $e$ is the identity matrix and $e_(i j)$ is a standard
matrix unit, with $1$ in position $(i,j)$ and zeros elsewhere. A transvection
$t_(i j)(xi)$ is a root unipotent corresponding to the root $e_i-e_j$, where
$e_i$ is the standard basis of the $(ell+1)$-dimensional Euclidean space
$RR^(ell+1)$.

For $ell ≥ 2$, the quotient group
$ K_1(Phi,R)=SK_1(ell+1,R)=SL(ell+1, R)/E(ell+1,R) $
is the usual (linear) unstable $K_1$-functor #citation[@bib:Bass1964,
  @bib:Bass1967, @bib:Bass1968, @bib:Milnor1971,
  @bib:Stepanov1987]. In rank one the corresponding coset space need not be a
quotient group, since $E(2,R)$ need not be normal, as discussed in
§@ss:rank-one.

The weight diagram of type $(A_ell,overline(omega)_1)$ is a chain:
#figure(type-a(), numbering: none)
where the bond marked by $i$ corresponds to the simple root
$alpha_i=e_i-e_(i+1)$. We put the $i$-th component $v_i$ of a vector $v$ from
the $(ell+1)$-dimensional representation module $V$ in the $i$-th node of the
diagram. Then the action of $t_(i j)(xi)=x_alpha (xi)$, $alpha=e_i-e_j$, adds
$xi v_j$ to $v_i$ and leaves the other coordinates unchanged.

=== The case $Phi = B_ell$ <ss:type-b>

Let us number the indices from $1$ to $2ell+1$ as follows:
$1,dots,ell,0,-ell,dots,-1$. Introduce on the free $R$-module $V=R^n$ of rank
$n=2ell+1$ the quadratic form
$ Q(x_1,dots,x_(-1))=x_0^2+x_1 x_(-1)+dots+x_ell x_(-ell). $
It has maximal Witt index, making $V$ a split orthogonal space of dimension
$2ell+1$ (an “Artin space”).

#source(252)
Then $G_("sc")(Phi,R)$ is the _spinorial group_ $Spin(n, R)$ defined by $Q$, and
$G_("ad")(Phi,R)$ is the _special orthogonal group_ $SO(n, R)=PSO(n, R)$. Recall
the equations defining $SO(n, R)$. For $a in GL(n, R)$ let $a_(i j)$ denote its
entry in position $(i,j)$, $a^(-1)=(a'_(i j))$ its inverse, and $a^t$ its
transpose. For simplicity we assume $2 in R^*$, although strictly speaking this
is not necessary. Write $sdiag(epsilon_1, dots, epsilon_n)$ for the matrix
having these entries on the skew diagonal (in the NE–SW direction) and zeros
elsewhere. For odd $n=2ell+1$ define
$ F=F_n=sdiag(1, dots, 1, 2, 1, dots, 1), $
with $ell$ ones on either side. Now $SO(2ell+1, R)$ consists of matrices
$a in GL(n, R)$ such that $det(a)=1$ and $a^t F_n a=F_n$. In terms of entries
the orthogonality condition is
$
  a'_(i j)=cases(
    a_(-j,-i) & "if " i j != 0 " or " i=j=0,
    a_(-j,0)/2 & "if " i=0 " and " j != 0,
    2a_(0,-i) & "if " j=0 " and " i != 0
  ).
$
To be a column of an orthogonal matrix, $x=(x_1,dots,x_(-1))$ must satisfy
$
  x_0^2+x_1 x_(-1)+dots+x_ell x_(-ell)=0
  quad "or" quad x_0^2+x_1 x_(-1)+dots+x_ell x_(-ell)=1,
$
according as the column has a nonzero index or index zero.

Recall the geometric interpretation used in chapter @ch:structure-theorems. Let
$V ≅ R^n$ have the standard basis $e_1,dots,e_n$, again denoted by
$e_1,dots,e_(-1)$. This identifies $GL(V)$ with $G=GL(n, R)$, acting on $V$ by
left multiplication. Fix the $R$-bilinear form whose matrix in this _Witt basis_
is $g=f_(2ell)$ if $n$ is even and $g=F_(2ell+1)$ if $n$ is odd. Thus
$(u,v)=B(u,v)=u^t g v$, and
$ (e_i,e_j)=delta_(i,-j)+delta_(i,0) delta_(j,0). $
The form is _symmetric_ and _nondegenerate_: the map $u |-> phi_u$
#source(253)
to the dual module $V^*=Hom(V, R)$, $phi_u (v)=(u,v)$, is an isomorphism. If
$2 in R^*$, then $O(n,R)$ is precisely the isometry group of $B$, consisting of
$g in G$ such that $(g u,g v)=(u,v)$, and $SO(n, R)=O(n,R) inter SL(n, R)$.

The root system $B_ell$ consists of $plus.minus e_i plus.minus e_j$
($1 <= i,j <= ell$, $i != j$) and $plus.minus e_i$, where $e_i$ is the canonical
basis of $RR^ell$; set $e_(-i)=-e_i$. The _elementary root unipotents_ have the
form
$ T_(i j)(xi)=T_(-j,-i)(-xi)=e+xi e_(i j)-xi e_(-j,-i) $
if $i,j != 0$ and $i != plus.minus j$. These are the _long root unipotents_ for
$e_i-e_j$ (so $e_i+e_j=e_i-e_(-j)$). The short-root unipotents corresponding to
$e_i=-e_(-i)$ have the form#ed-note[These formulas use the stated action on
  columns. In particular the short-root matrix preserves
  $x_0^2+sum_(i=1)^ell x_i x_(-i)$. The row-vector convention requires
  transposing the corresponding formulas.]
$ T_(i 0)(xi)=e+2xi e_(i 0)-xi e_(0,-i)-xi^2 e_(i,-i). $


The elements $T_(i j)(xi)$, $xi in R$, form the _elementary unipotent root
subgroup_ $X_(i j)$, also called a _root subgroup_. It is long if $i,j != 0$ and
short if one index is zero. The subgroup generated by all root subgroups is the
_elementary subgroup_ $EO(n, R)$. Analogously one defines the elementary
spinorial group $Epin(n, R)$. These are respectively $E_("ad")(Phi,R)$ and
$E_("sc")(Phi,R)$.

Although $Spin(n, K)=Epin(n, K)$ for a field $K$, $EO(n, K)$ need not equal
$SO(n, K)$. It is the kernel of the _spinorial norm_, generally a proper
subgroup; apart from very small dimensions it equals the commutator subgroup
$Omega(n, K)$. Thus
$ K_1(B_ell,R)=Spin(2ell+1, R)/Epin(2ell+1, R) $
differs from the Bass orthogonal $K_1$-functor
$ KO_1(n,R)=SO(n, R)/EO(n, R), $
#source(254)
see #citation[@bib:Bass1974, @bib:Bak1981, @bib:Stein1978,
  @bib:Stepanov1987].

The weight diagram $(B_ell,overline(omega)_1)$ is a chain:
#figure(type-b(), numbering: none)
with $alpha_i=e_i-e_(i+1)$ for $1 <= i <= ell-1$, and $alpha_ell=e_ell$. We
write $e_(-i)$ rather than $-e_i$ to conform with the numbering of basis vectors
and coordinates. For $alpha=e_i-e_j$ the action of $T_(i j)(xi)=x_alpha (xi)$
adds $xi v_j$ to $v_i$ and $-xi v_(-i)$ to $v_(-j)$. For $alpha=e_i$ it adds
$-xi v_(-i)$ to $v_0$ and $2xi v_0-xi^2 v_(-i)$ to $v_i$. Other coordinates
remain unaltered.

=== The case $Phi = C_ell$ <ss:type-c>

Let us number the indices from $1$ to $2ell$ as follows:
$1,dots,ell,-ell,dots,-1$. Introduce on the free $R$-module $V=R^n$, $n=2ell$, a
symplectic form by
$
  B(x,y)=(x_1 y_(-1)-x_(-1) y_1)+dots
  +(x_ell y_(-ell)-x_(-ell) y_ell),
$
for $x=(x_1,dots,x_(-1))$, $y=(y_1,dots,y_(-1)) in V$. Then $G_("sc")(Phi,R)$ is
isomorphic to the _symplectic group_ $Sp(2ell, R)$, defined by this form, and
the adjoint group scheme is the corresponding projective group $PSp_(2ell)$.
Recall the equations for the matrix entries of elements of $Sp(2ell, R)$. For
even $n=2ell$ define the matrix
$ F=F_(2ell)=sdiag(1, dots, 1, -1, dots, -1), $
where the series of $1$'s and $(-1)$'s consist of $ell$ members each. Then
$Sp(2ell, R)$ consists of matrices $a in GL(n, R)$ for which
$a^t F_(2ell) a=F_(2ell)$. A matrix $a=(a_(i j))$ is symplectic if and only if
$ a'_(i j)=epsilon_i epsilon_j a_(-j,-i), $
where $epsilon_i$ is the sign of $i$, i.e. $epsilon_i=1$ if $1 <= i <= ell$ and
$epsilon_i=-1$ if $-ell <= i <= -1$.

Recall that the root system of type $C_ell$ is dual to that of type $B_ell$ and
consists of the roots $plus.minus e_i plus.minus e_j$ ($1 <= i,j <= ell$,
$i != j$) and $plus.minus 2e_i$. As before, $e_i$ is the canonical basis of
$RR^ell$ and $e_(-i)=-e_i$. The _elementary root unipotents_ have the form
$ T_(i,-i)(xi)=e+xi e_(i,-i) $
#source(255)
if the indices are opposite (the _long root unipotents_, corresponding to
$2e_i$), and the form
$
  T_(i j)(xi)=T_(-j,-i)(-epsilon_i epsilon_j xi)
  =e+xi e_(i j)-epsilon_i epsilon_j xi e_(-j,-i)
$
if $i != plus.minus j$ (the _short root unipotents_, corresponding to
$e_i-e_j$). Let $i != j$. All root unipotents $T_(i j)(xi)$ form the _root
subgroup_ $X_(i j)={T_(i j)(xi):xi in R}$. The subgroup of $Sp(2ell, R)$
generated by all root subgroups is called the _elementary symplectic subgroup_
and denoted by $Ep(2ell, R)$. For $ell ≥ 2$,
$ K_1(C_ell,R)=KSp_1(2ell,R)=Sp(2ell, R)/Ep(2ell, R) $
is the ordinary _symplectic_ $K_1$-functor #citation[@bib:Bass1967,
  @bib:Stepanov1987].

The weight diagram of type $(C_ell,overline(omega)_1)$ is a chain:
#figure(type-c(), numbering: none)
where bonds marked by $i$ correspond to $alpha_i=e_i-e_(i+1)$ for
$1 <= i <= ell-1$ and $alpha_ell=2e_ell$. The action of
$T_(i j)(xi)=x_alpha (xi)$ on $v in V$ has the following effect. For
$alpha=e_i-e_j$ it adds $xi v_j$ to $v_i$ and $-epsilon_i epsilon_j xi v_(-i)$
to $v_(-j)$. For $alpha=2e_i$ it adds $xi v_(-i)$ to $v_i$. In both cases all
other coordinates remain unaltered.

=== The case $Phi = D_ell$ <ss:type-d>

Keep the same numbering of indices as for $C_ell$ and introduce on the free
$R$-module $V=R^n$, $n=2ell$, a quadratic form by
$ Q(x_1,dots,x_(-1))=x_1 x_(-1)+dots+x_ell x_(-ell). $
This form has maximal Witt index and makes $V$ an Artin space. Then
$G_("sc")(Phi,R)$ is again the _spinorial group_ $Spin(n, R)$ defined by $Q$,
and the adjoint group scheme is $PSO_n$. For one of the lattices $P$ lying
strictly between $Q(Phi)$ and $P(Phi)$ (there is one if $ell$ is odd, three if
$ell$ is even) we have $G_P (Phi,R)=SO(n, R)$. Recall the equations for this
latter group, assuming $2 in R^*$ for this matrix description. Over arbitrary
rings, $SO_(2ell)$ means the split connected special orthogonal group scheme of
$Q$; preserving its polar form and having determinant one is insufficient in
characteristic $2$
#citation[@bib:Conrad2014, Appendix C, Definition C.2.10 and Theorem C.2.11]
#citation[@bib:Conrad2015, Example 2.9]. For even $n=2ell$ define
$ f=f_n=sdiag(1, dots, 1), quad f_(i j)=delta_(i,-j). $
Now $SO(2ell, R)$ consists of matrices $a in GL(2ell, R)$ for which $det(a)=1$
and $a^t f_n a=f_n$.

#source(256)
In terms of entries the orthogonality condition is $a'_(i j)=a_(-j,-i)$. To be a
column of an orthogonal matrix, $x=(x_1,dots,x_(-1))$ has to satisfy
$x_1 x_(-1)+dots+x_ell x_(-ell)=0$.

The root system of type $D_ell$ consists of the long roots of $B_ell$, namely
$plus.minus e_i plus.minus e_j$ for $1 <= i,j <= ell$, $i != j$. The _elementary
root unipotents_ are precisely the long root unipotents, and thus have the form
$ T_(i j)(xi)=T_(-j,-i)(-xi)=e+xi e_(i j)-xi e_(-j,-i) $
for $i != plus.minus j$. They generate the subgroup $EO(2ell, R)$ of
$SO(2ell, R)$, called the _elementary orthogonal group_. All comments from the
$B_ell$ case apply here. Again the functor
$ K_1(D_ell,R)=Spin(2ell, R)/Epin(2ell, R) $
does not in general coincide with the Bass functor $KO_1(n,R)$.

The weight diagram of type $(D_ell,overline(omega)_1)$ is _not_ a chain:
#figure(type-d(), numbering: none)
where bonds marked by $i$ correspond to $alpha_i=e_i-e_(i+1)$ for
$1 <= i <= ell-1$ and $alpha_ell=e_(ell-1)+e_ell$. The action of
$T_(i j)(xi)=x_alpha (xi)$ on $v in V$ has the same effect as in the $B_ell$
case: for $alpha=e_i-e_j$ it adds $xi v_j$ to $v_i$ and $-xi v_(-i)$ to
$v_(-j)$, leaving other coordinates unaltered.

The identifications for the classical cases go back to R. Ree
#citation[@bib:Ree1957] and J. Dieudonné #citation[@bib:Dieudonne1957] (where
the orthogonal group over a nonperfect field of characteristic $2$ was treated).
See J.-I. Hee #citation[@bib:Hee1984] for a modern exposition. For exceptional
cases, identifications with groups stabilizing systems of tensors are far less
commonly known. Here we describe $G_2$, also studied by Ree. The group of type
$G_2$ is in many respects extremely close to classical groups and should be
considered one—or else groups of types $D_4$ and $B_3$ should be regarded as
exceptional. We discuss this subject in the next two sections.

#source(257)
It is already much more difficult to describe explicitly the equations for
spinorial groups. R. Brown #citation[@bib:Brown1971] showed that split spinorial
groups may be characterized as stabilizers of a bilinear form $B$ and a tensor
of valency four (he considered a linear map $V ⊗ V -> V ⊗ V$, which can be
transformed into a four-linear form using the pairing induced by $B$).

=== The case $Phi = G_2$ <ss:type-g2>

Let $V=R^7$ be a free $R$-module with vector coordinates numbered by
$1,2,3,0,-3,-2,-1$. Introduce the quadratic form
$ Q(x)=-x_0^2+x_1 x_(-1)+x_2 x_(-2)+x_3 x_(-3), $
where $x=(x_1,x_2,x_3,x_0,x_(-3),x_(-2),x_(-1)) in V$, and an alternating
trilinear form $F(x,y,z)$ defined by the monomials
$
  x_0 x_1 x_(-1)+x_0 x_2 x_(-2)+x_0 x_3 x_(-3)
  +x_1 x_2 x_3+x_(-1) x_(-2) x_(-3).
$
Each monomial is alternated to produce a trilinear form. Thus the first monomial
contributes
$
  x_0 y_1 z_(-1)+y_0 z_1 x_(-1)+z_0 x_1 y_(-1)
  -x_0 z_1 y_(-1)-y_0 x_1 z_(-1)-z_0 y_1 x_(-1).
$
The form $F$ is usually called the _Dickson form_, or _alternating Dickson form_
(see the next section).

The group $Isom(Q, F, R)$ consists of transformations $g in GL(V)=GL(7, R)$ such
that $Q(g x)=Q(x)$ and $F(g x,g y,g z)=F(x,y,z)$ for all $x,y,z in V$. When
$2 in R^*$, this is the Chevalley group $G(G_2,R)$. The field identification
goes back to Ree #citation[@bib:Ree1957]. The octonion automorphism realization
below is valid over every commutative ring; when $2$ is invertible it also
proves the identification with $Isom(Q, F, R)$.#ed-note[The quadratic form and
  the passage to general rings are corrected using the split octonion algebra;
  see
  #citation[@bib:Asok2019, Definition 2.1.9 and Theorem 2.2.1]
  and #citation[@bib:Conrad2015, Theorem B.14].]

Let $cal(O)$ be the split Zorn octonion algebra, whose elements are
$(a,u,v,b) in R ⊕ R^3 ⊕ R^3 ⊕ R$. Its multiplication is
$
  (a,u,v,b)(c,w,z,d)=(a c-u dot z,
    a w+d u+v times z,c v+b z+u times w,b d-v dot w),
$
where $dot$ denotes the scalar product and $times$ the ordinary
three-dimensional cross product. Its unit is $(1,0,0,1)$, norm is
$N(a,u,v,b)=a b+u dot v$, and trace is $a+b$. For every commutative ring $R$,
the automorphism group scheme of this algebra is split of type $G_2$
#citation[@bib:Conrad2015, Theorem B.14]\; in particular
$ G(G_2,R)=Aut_(R"-alg")(cal(O)). $

If $2 in R^*$, write $cal(O)=R 1 ⊕ V$, where $V$ is its trace-zero submodule.
Identify the displayed coordinates with
$X=(x_0,(x_1,x_2,x_3),(x_(-1),x_(-2),x_(-3)),-x_0)$. Then $N(X)=Q(x)$. Write
$B(X,Y)=N(X+Y)-N(X)-N(Y)$; its restriction to $V$ is nondegenerate, and direct
multiplication gives the above Dickson form as $F(X,Y,Z)=B(X Y,Z)$. For
$X,Y in V$ the product has the unique form
$
  X Y=-B(X,Y)/2 dot 1+X times Y, quad
  B(X times Y,Z)=F(X,Y,Z).
$
Thus $Q$ and $F$ determine the multiplication: nondegeneracy of $B$ determines
$X times Y$, and the scalar part is $-B(X,Y)/2$. An isometry of $Q$ and $F$
consequently extends, by fixing $1$, to an automorphism of $cal(O)$. Conversely
every octonion automorphism preserves trace, norm and multiplication, hence both
forms. This proves the claimed identification over every ring in which $2$ is a
unit.

The weight diagram of type $(G_2,overline(omega)_1)$ is a chain:
#figure(type-g(), numbering: none)
where $alpha_1$ is short and $alpha_2$ is long. The action of any root unipotent
on the seven-dimensional module can be read off the diagram, apart from the
signs.

#source(258)
For example, to determine the action for $alpha=2alpha_1+alpha_2$, we find all
paths whose bond marks are $1,1,2$ in any order, and their composite paths. In
the chosen Zorn basis the root parametrization can be fixed so that the
transformed coordinates are
$
  v'_1 = v_1 + 2xi v_0 + xi^2 v_(-1), quad
  v'_0 = v_0 + xi v_(-1), \
  v'_(-2) = v_(-2) - xi v_3, quad
  v'_(-3) = v_(-3) + xi v_2,
$
<eq:g2-short-root-action>
with all other coordinates unchanged. The coefficients and directions agree with
both $Q$ and the Dickson form. This transformation extends integrally to the
Zorn algebra: replace $a,b,u_1,v_2,v_3$ respectively by $a+xi v_1$, $b-xi v_1$,
$u_1+xi(a-b)+xi^2 v_1$, $v_2-xi u_3$, and $v_3+xi u_2$, fixing the remaining
coordinates. It preserves multiplication and satisfies
$x_alpha (xi)x_alpha (eta)=x_alpha (xi+eta)$ over every commutative
ring.#ed-note[
  The printed example's coefficients and arrow directions are incompatible with
  the displayed Dickson form. Here the coordinate order and root parametrization
  agree with the Zorn basis used above.
] For alternative root normalizations see #citation[@bib:Hurrelbrink1975].

The cases $(A_ell,overline(omega)_1)$, $(B_ell,overline(omega)_1)$,
$(C_ell,overline(omega)_1)$ and $(G_2,overline(omega)_1)$ considered above are
the chain cases in this list; their dual modules have the same chain shape. For
all other cases a complete order on vector coordinates—and thus on columns and
rows of a matrix expressing an endomorphism of the representation—is of no real
value and may be misleading or even obnoxious. It is convenient to think of
coordinates, columns and rows as _partially ordered_. Even for
$(D_ell,overline(omega)_1)$ it is an offence to the nature of things to claim
that the $ell$-th coordinate precedes the $(-ell)$-th coordinate.
