#import "main-defs.typ": *
#import "statements.typ": lemma, theorem
#import "diagrams/e6-examples.typ": e6-dynkin, e6-graph
#let Isom = group-name("Isom")

== The cubic form for $E_6$ <sec:cubic-form>

In this section we describe a realization of the simply connected Chevalley
group $G=G_("sc")(E_6,R)$ as the isometry group of a cubic form on a free module
of rank $27$, which gives full control of the equations satisfied by the entries
of matrices from $G$. This is our crucial example and we discuss it in some
detail. It is already much more sophisticated than the classical cases, but the
underlying structure is still much more transparent and easy to check than for
the senior cases $E_7$ and $E_8$, or even for the subordinate case $F_4$.
Analogous constructions for other exceptional groups are sketched in the next
section.

=== The 27-dimensional module <ss:e6-module>

The module $(V,pi)$ of $G=G(E_6,R)$ with highest weight
$omega=overline(omega)_1$ has dimension $27$. Its dual $V^*$ has highest weight
$overline(omega)_6$. The weight diagram for $(E_6,overline(omega)_1)$ gives a
more realistic image of weight diagrams.

#source(259)
#figure(e6-graph(), numbering: none)
The nodes correspond to weights $lambda in Lambda=Lambda(pi)$, all of
multiplicity $1$ since they form a single Weyl orbit. The numbering of
fundamental roots follows Bourbaki #citation[@bib:Bourbaki2002, Chapter VI,
  Plate V]:
#figure([#diagram(e6-dynkin())], numbering: none)
This is our critical example. It is also the diagram of cosets $W(E_6)/W(D_5)$,
two cosets being joined by a bond marked $i$ if and only if one passes from one
to the other by the fundamental reflection $w_i$; see
#citation[@bib:Curtis1971]. Indeed the stabilizer of the highest weight is
generated by all fundamental reflections apart from $w_1$.

Think of $v in V$ as a weighted diagram, with $v_lambda in R$ put into the node
corresponding to $lambda$. The action of $x_alpha (xi)$ is easily recovered. For
a positive root, decompose $alpha=alpha_(i_1)+dots+alpha_(i_s)$ and find paths
whose bond marks are $i_1,dots,i_s$ in any order. For a negative root, reverse
the paths for $-alpha$. Every root gives six distinct pairs of endpoint weights,
although several paths may have the same endpoints. If a path starts at $lambda$
and finishes at $nu$, the corresponding elementary action adds
$plus.minus xi v_lambda$ to $v_nu$. For example, for
$alpha=alpha_1+alpha_3+alpha_4$, the six coordinate pairs are marked by crosses
and squares:

#source(260)
#figure([#diagram(e6-graph(mark-action: true))], numbering: none)
An explicit description of the signs is a different story. Since this
representation appears as a subrepresentation of the adjoint module of $E_7$,
the signs can be obtained from the structure constants $N_(alpha beta)$ for its
Lie algebra; see #citation[@bib:Mizuno1980, @bib:Gilkey1988]. The original
survey announced a table in a forthcoming paper by the author and E. B. Plotkin.
An alternative description uses the Frenkel–Kac cocycle
#citation[@bib:Frenkel1980, @bib:Springer1981, @bib:Frenkel1988].

=== The cubic form <ss:e6-cubic>

The first realization of simply connected $E_6$ as the isometry group of a
trilinear form on a 27-dimensional space was obtained by L. E. Dickson in 1905.
It is usually called the _Dickson form_, or the _symmetric Dickson form_ to
distinguish it from the alternating Dickson form used for $G_2$. In 1950 C.
Chevalley and R. D. Schafer discovered a construction of $E_6$ and $F_4$ in
terms of the 27-dimensional _exceptional Jordan algebra_, an algebra of
Hermitian matrices over the _Cayley–Dickson_ (octonion) algebra
#citation[@bib:Chevalley1950]. Finally in 1952 H. Freudenthal gave an extremely
beautiful construction which we reproduce below. Dickson's original form
displays symmetry with respect to $A_5+A_1$; analogous realizations were used by
Chevalley #citation[@bib:Chevalley1951], E. Shult and M. Aschbacher
#citation[@bib:Aschbacher1987a]. Octonion constructions are related to $D_4$ and
$F_4$, whereas in Freudenthal's construction the symmetry with respect to $3A_2$
is apparent. Freudenthal considered characteristic $0$. Subsequent works
extended the realizations to fields of characteristic different from $2$ and
$3$; see #citation[@bib:Jacobson1961, @bib:Seligman1960, @bib:Springer1960,
  @bib:Springer1962b, @bib:Springer1968, @bib:Veldkamp1968, @bib:Cohen1988a,
  @bib:Faulkner1977] and their references.

#source(261)
Springer #citation[@bib:Springer1962a] characterized the cubic form
axiomatically. It is the norm form of the exceptional Jordan algebra. Let
$M(3,R)$ be the full matrix ring of degree $3$ and
$V={(x,y,z):x,y,z in M(3,R)}$, a free $M(3,R)$-module of rank $3$, hence a free
$R$-module of rank $27$. Define
$ F(x,y,z)=det(x)+det(y)+det(z)-tr(x y z). $
The minus sign in the trace term agrees with the later exposition
#citation[@bib:Vavilov1996, §8, p. 93]. Then $G_("sc")(E_6,R)$ is the isometry
group $Isom(F, R)$ of all $g in GL(V)=GL(27, R)$ satisfying the polynomial
identity $F(g(x,y,z))=F(x,y,z)$ after arbitrary base change
#citation[@bib:Conrad2015, formula (6.6) and Theorem C.2].#ed-note[
  The weight-basis cubic of §@ss:e6-weight-cubic is integrally isometric to this
  norm by a signed permutation of its basis. An explicit certificate and the
  full polynomial identity over $ZZ$ are provided in the Sage verification:
  #link(
    "https://github.com/stdcall/vavilov-1991/blob/main/checks/sage/"
      + "e6_norm_model.py",
  ). The unimodular isometry conjugates the two stabilizer schemes over $ZZ$ and
  after every commutative base change.
] Characteristic $2$ and $3$ require care, but do not obstruct this realization.
The original survey outlined an elementary field argument in the spirit of the
Ree–Dieudonné proof presented by Hee #citation[@bib:Hee1984]. Below we retain
its geometric intuition and use the scheme argument for the identification over
arbitrary rings. We also describe a construction of the cubic form symmetric
under the whole Weyl group $W(E_6)$.

The form emerges when one seeks a nontrivial degenerate form invariant under the
extended Weyl group $tilde(W)(E_6)$ on the 27-dimensional space. Classical
semisimple groups arise as isometry groups of nondegenerate bilinear forms. Here
degeneracy is essential. For a homogeneous form of degree at least $3$, we use
nondegeneracy to mean that the projective hypersurface $F=0$ is smooth;
degeneracy means singularity. The classical theorem of
Jordan–Lie–Burnside–Hurwitz–Bott–Tate–Matsumura–Monsky–Mumford–Ax–Sah–
Orlik–Solomon–Suzuki and others says that in characteristic $0$ the isometry
group of a nondegenerate form of degree at least $3$ is finite; see
#citation[@bib:Orlik1978; @bib:Esser2024, Theorem 3.1 and Remark 3.2]. For
exceptional groups the interesting forms are precisely the exceptional ones.

#source(262)
For a fixed algebraically closed field it is easy to find some tensor whose
stabilizer is a given semisimple group. Subject to explicitly listed exceptions,
irreducible tensor-indecomposable semisimple subgroups are maximal among closed
connected subgroups of the ambient classical groups. In characteristic $0$ this
is Dynkin's theory #citation[@bib:Dynkin1957a, @bib:Dynkin1957b]\; the
positive-characteristic case was established in work of Seitz, Suprunenko and
Testerman #citation[@bib:Seitz1987, @bib:Seitz1991, @bib:Testerman1988]. One may
therefore choose a tensor fixed by the group but not the ambient classical
group. The real problem is a characteristic-independent invariant with simple
and convenient equations.

=== The exceptional Jordan algebra <ss:e6-jordan>

Let $K$ have characteristic different from $2$ and $3$. Let $C$ be the split
octonion algebra over $K$ with quadratic norm $N$, the unique eight-dimensional
composition algebra with zero divisors: $N(x y)=N(x)N(y)$. Its matrix
realization and further references are in #citation[@bib:Faulkner1977]. Write
$x |-> x^*$ for the canonical involution and $T(x)=x+x^*$ for the trace. Choose
$gamma_1,gamma_2,gamma_3 in K^*$ and set $g=diag(gamma_1, gamma_2, gamma_3)$.
The involution on $M(3,C)$ is $a |-> g^(-1)(a^*)^t g$. The Hermitian matrices
form the space $J$ of matrices
$
  a=mat(
    alpha_1, x_3, gamma_1^(-1) gamma_3 x_2^*;
    gamma_2^(-1) gamma_1 x_3^*, alpha_2, x_1;
    x_2, gamma_3^(-1) gamma_2 x_1^*, alpha_3
  ).
$
It is closed under the product $a b=(a dot b+b dot a)/2$, where $dot$ denotes
ordinary matrix multiplication over $C$. With this product $J$ is an exceptional
Jordan algebra #citation[@bib:Faulkner1977]. The following diagram shows how the
three scalar components and three octonion components occupy the 27-dimensional
space.

#source(263)
#figure(e6-graph(mode: "jordan"), numbering: none)
The three isolated nodes correspond to $alpha_1,alpha_2,alpha_3$, and the three
eight-dimensional components to $x_1,x_2,x_3$. The determinant formula
$
  det(a)=alpha_1 alpha_2 alpha_3+T((x_1 x_2)x_3)
  -alpha_1 gamma_3^(-1) gamma_2 N(x_1)
  -alpha_2 gamma_1^(-1) gamma_3 N(x_2)
  -alpha_3 gamma_2^(-1) gamma_1 N(x_3)
$
defines the cubic form on $J$. In characteristic different from $2$ and $3$, one
may polarize it to a symmetric trilinear form $f$ normalized by
$f(x,x,x)=det(x)$.

The form also provides a useful binary operation. Define a nondegenerate
quadratic form on $J$ by
$
  Q(a)=(alpha_1^2+alpha_2^2+alpha_3^2)/2
  +gamma_3^(-1) gamma_2 N(x_1)
  +gamma_1^(-1) gamma_3 N(x_2)
  +gamma_2^(-1) gamma_1 N(x_3).
$
If $( , )$ denotes its polarization, the traditional _Freudenthal cross product_
satisfies $(x times y,z)=3f(x,y,z)$. It differs from the usual Jordan product by
a linear combination of $x$, $y$ and the identity $e$. The Jordan structure
contains more than is needed to recover $E_6$, and the required formulas concern
the cross product instead. Moreover the quadratic form is extra structure from
$F_4$, not $E_6$-invariant. We must therefore distinguish $V$ and $V^*$
carefully. Regard vectors in $V$ as columns and in $V^*$ as rows, with the
natural pairing given by multiplication. A trilinear form defines
$V times V -> V^*$ by $(x times y)z=f(x,y,z)$; a product of two columns is a
row, and analogously a product of two rows is a column. The exceptional Jordan
algebra also has the distinguished element $e$, #source(264) the sum
$e=e_(1 1)+e_(2 2)+e_(3 3)$ of three primitive idempotents; compare the
distinguished weight triple in §@ss:e6-weight-cubic.

=== The Dickson–Chevalley–Aschbacher construction <ss:e6-dickson>

In contrast to the preceding $D_4$ symmetry, this construction uses $A_5+A_1$
symmetry:
#figure([#diagram(e6-graph(mode: "a5-a1"))], numbering: none)
The space is $V=U ⊕ Λ^2 U^* ⊕ U$, for the six-dimensional natural representation
$U$ of $SL(6, R)=G(A_5,R)$, or alternatively $V=U ⊕ Λ^4 U ⊕ U$. The form is
determined by the natural pairing or intersection product. For a detailed
description with explicit signs, see #citation[@bib:Aschbacher1987a].

=== One more construction <ss:e6-weight-cubic>

Consider the _weight graph_ instead of the weight diagram: its nodes are the
same, but two distinct weights are joined whenever their difference is any root,
rather than only a fundamental root. This is the remarkable distance-transitive
Schläfli graph of _diameter_ $2$; see #citation[@bib:Coxeter1963]. Each node has
$16$ neighbours and $10$ non-neighbours. The latter are marked by white squares
relative to the highest weight, marked by a black square:
#figure([#diagram(e6-graph(mode: "neighbours"))], numbering: none)

#source(265)
These ten weights form the diagram $(D_5,overline(omega)_1)$; the other sixteen
form its half-spinorial diagram. We seek a cubic invariant under the extended
Weyl group $tilde(W)(E_6)$ with as few monomials as possible. An invariant
containing $x_lambda y_mu z_nu$ for adjacent $lambda,mu$ must contain fifteen
more such terms, but for nonadjacent $lambda,mu$ only nine more. Symmetry
suggests using triples of pairwise nonadjacent weights. Every nonadjacent pair
has exactly one third weight nonadjacent to both. For example:
#figure([#diagram(e6-graph(mode: "triple"))], numbering: none)

Write $Theta$ and $Theta_0$ for ordered and unordered triples:
$
  Theta={(lambda,mu,nu) in Lambda^3:
    lambda-mu,lambda-nu,mu-nu ∉ Phi union {0}},
$
$ Theta_0={ {lambda,mu,nu}: (lambda,mu,nu) in Theta }. $
Two members determine the third uniquely. The Weyl group acts transitively on
both sets. The stabilizer of the highest weight and its largest non-neighbour is
generated by all fundamental reflections except $w_1$ and $w_6$, so
$Theta ≅ W(E_6)/W(D_4)$. Consequently $abs(Theta)=270$ and $abs(Theta_0)=45$.
Under the identification with the 27 lines on a cubic surface, these 45 triples
are the tritangent plane sections. The displayed triple is maximal #source(266)
in lexicographic order; call it the _distinguished triple_
$(lambda_0,mu_0,nu_0)$, with $lambda_0=omega$.

In this weight construction we use the complete, unscaled polarization, whose
diagonal is $6F(x)$; this differs from the normalization $f(x,x,x)=det(x)$ in
the preceding Jordan model.

Define the cubic and symmetric trilinear forms in the weight basis $v^lambda$,
$lambda in Lambda$, by
$
  F(x)=sum_({lambda,mu,nu} in Theta_0)
  c_(lambda mu nu) x_lambda x_mu x_nu,
$
$
  f(x,y,z)=sum_((lambda,mu,nu) in Theta)
  c_(lambda mu nu) x_lambda y_mu z_nu,
$
where the coefficients $c_(lambda mu nu)$ are signs, unchanged by permuting the
triple. Their common overall sign may be fixed by taking the distinguished
coefficient to be $+1$. Invariance under the extended Weyl group then determines
all signs uniquely. Indeed, every element of $T(E_6,ZZ)$ changes an even number
of signs among the three basis vectors of each triple. It suffices to check this
for the distinguished triple. The group is generated by $h_alpha (-1)$, and
$h_alpha (epsilon)$ multiplies six basis vectors by $epsilon$ and six by
$epsilon^(-1)$. The stabilizer $W(D_4)$ of the ordered distinguished triple
contributes no sign ambiguity: its simple root strings through these three
weights are singletons, so its standard lifts fix their basis vectors. Together
with the preceding torus calculation, this makes the transport of signs
independent of the chosen lift. For $alpha=alpha_1$ the affected nodes are
marked below:
#figure([#diagram(e6-graph(mode: "root-torus"))], numbering: none)
Pluses mean multiplication by $epsilon$, minuses by $epsilon^(-1)$. Both
$h_(alpha_1)(-1)$ and $h_(alpha_6)(-1)$ change two signs in the distinguished
triple, and the other simple root elements change none. To determine a
coefficient choose $n_w in tilde(W)(E_6)$ with
$w(lambda_0,mu_0,nu_0)=(lambda,mu,nu)$, and use $+1$ or $-1$ according as the
images of the three basis vectors have an even or odd number of sign changes.
The Frenkel–Kac cocycle gives a less cumbersome expression for the same rule.

#source(267)
Even if $2$ and $3$ are not units, the coefficients of $F$ can be read from $f$
in this fixed weight basis and with this prescribed square-free support. The
diagonal identity is $f(x,x,x)=6F(x)$; it cannot recover $F$ by division in
characteristics $2$ or $3$.

The weight elements of §@sec:elementary-calculations can change an odd number of
signs. The eigenvalue calculation #citation[@bib:Vavilov1988a, Theorem 1] shows
that $h_(overline(omega)_1)(epsilon)$ has one eigenvalue $epsilon$, ten
$epsilon^(-1)$ and sixteen $1$'s:
#figure([#diagram(e6-graph(mode: "weight-torus"))], numbering: none)
The form is only a relative invariant for the extended Chevalley group: it may
be multiplied by a scalar factor.

On basis vectors the product defined by $f$ is zero for adjacent or equal
weights. For nonadjacent weights it is
$v^lambda times v^mu=c_(lambda mu nu) v_nu$, with the unique third weight $nu$
and its dual basis vector $v_nu$. Extend by bilinearity. The product $x times x$
has a factor $2$, so vanishes in characteristic $2$. A quadratic refinement is
needed, as in Aschbacher's approach #citation[@bib:Aschbacher1987a]. Define

#source(268)
$
  ell(x, y)=sum_({lambda,mu,nu} in Theta_0) c_(lambda mu nu)
  (x_lambda x_mu y_nu+x_lambda x_nu y_mu+x_mu x_nu y_lambda).
$
This is quadratic in $x$ and linear in $y$, and is the coefficient of $t$ in
$F(x+t y)$. Define the _quadratic adjoint_ $x^sharp in V^*$ by
$x^sharp y=ell(x, y)$, and its polarization by
$x times y=(x+y)^sharp-x^sharp-y^sharp$. These formulas work over every
commutative ring, with $f(x,x,y)=2ell(x, y)$.

=== The identification <ss:e6-identification>

#theorem[
  Let $R$ be a commutative ring with $1$, and let $F$ be the integral cubic norm
  in the weight basis of §@ss:e6-weight-cubic. Its group scheme of linear
  isometries is the split simply connected Chevalley group of type $E_6$.
  Consequently, $G_("sc")(E_6,R)=Isom(F)(R)$ for every $R$.
] <th:e6-cubic-isometry>

Here $Isom(F)(R)$ means the invertible linear substitutions preserving the cubic
polynomial after arbitrary base change. Over rings in which $6$ is invertible
this is equivalent to preserving its symmetric polarization $f$. The cubic
formulation retains the information needed in all characteristics.#ed-note[
  The original statement used $Isom(f)$ and asserted that checking fields
  sufficed for the group scheme identification. We use the cubic norm and the
  scheme theorem of Conrad #citation[@bib:Conrad2015, Theorem C.2]. A comparison
  of geometric points alone does not establish a group scheme isomorphism.
]

We indicate the scheme argument. In the model $M=op("Mat")_3(ZZ)^3$ with
$F(x,y,z)=det x+det y+det z-tr(x y z)$, the action of $(SL_3)^3 / mu_3$ supplies
a split maximal torus of rank six. The tangent-space calculation gives dimension
$78$ in every characteristic and proves smoothness of the fibres. Flatness, the
root-space calculation, and a connectedness argument then identify the full
stabilizer as a simply connected semisimple group scheme of type $E_6$. These
steps, including small characteristics, are proved in Conrad
#citation[@bib:Conrad2015, Lemmas C.3–C.4 and proof of Theorem C.2].

The original field argument provides useful geometric intuition. Root unipotents
preserve the cubic norm, which can be checked directly on its 45 monomials. Weyl
group conjugacy reduces this calculation to one root. For the following
geometric illustration, let $K$ be algebraically closed and of characteristic
different from $2$ and $3$. Call a nonzero vector $x$ _white_ if $x^sharp=0$,
_grey_ if $F(x)=0$ but $x^sharp !=0$, and _black_ if $F(x)!=0$. In the Jordan
model these are the three ranks, $1$, $2$, and $3$. Typical representatives are
$v^lambda$, $v^lambda+v^mu$, and $v^lambda+v^mu+c v^nu$, where the three weights
form a cubic triple and $c!=0$. These definitions also work in characteristics
$2$ and $3$.
#source(269)
There is one orbit of white vectors and one orbit of grey vectors; black vectors
form one orbit under the extended group, and their nonzero norm values
distinguish their orbits under $E_6$. This is geometric orbit information; it
does not assert a classification of rational orbits over an arbitrary field. For
the historical study of these orbits, see #citation[@bib:Mars1966].

A cubic isometry therefore has a white first column. By multiplying on the left
by an element of $E_6(K)$, one can make that column the highest weight vector.
The incidence relations among the weights then force a block triangular matrix
with block sizes $1$, $16$, and $10$:
$ a g=mat(1, *, *; 0, *, *; 0, 0, *). $
#source(270)
The analogous operation on the dual module normalizes the first row and leads to
a block diagonal matrix of the same sizes. The two nontrivial blocks reflect the
half-spin and vector representations of the Levi subgroup of type $D_5$.

On the ten-dimensional subspace $U$ spanned by weights nonadjacent to the
highest weight $omega$, the expression $B(u,v)=f(v^omega,u,v)$ is a
nondegenerate split bilinear form. Its preservation gives the familiar
orthogonal equations on the $10 times 10$ block. This explains the role of the
orthogonal group in the reduction. Identifying the other block and the full
stabilizer requires the additional representation and scheme arguments supplied
above; the orthogonal equations alone do not finish the proof.

#source(271)
The corresponding extended group preserves the cubic norm up to a unit
multiplier. Thus its elements satisfy $F(g x)=epsilon F(x)$, with
$epsilon in R^*$; when $6$ is invertible, this is equivalently
$f(g x,g y,g z)=epsilon f(x,y,z)$. These descriptions provide practical
equations for the entries of matrices in the ordinary and extended groups, and
will be used in the subsequent sections.
