#import "main-defs.typ": *
#import "diagrams/exceptional-weights.typ": exceptional-graph
#let pf = math.op("pf")
#let Isom = group-name("Isom")

== A phoenix view of other exceptional groups <sec:other-exceptional-groups>

Chuang Chow contrasts a bird which flies so high that it cannot distinguish the
details below with one which never rises above its own marsh. Different horizons
lead to different thoughts. This section takes the phoenix's view: we sketch the
other exceptional groups, leaving much of the detail aside.

=== The case $Phi=F_4$ <ss:type-f4>

Groups of type $F_4$ occur as stabilizers of suitable black vectors in the
27-dimensional representation of $E_6$. Different orbits give different forms of
$F_4$, some nonsplit #citation[@bib:Tits1966a, @bib:Satake1971]. For the split
octonion algebra, the split group $F_4$ is the automorphism group of the
exceptional Jordan algebra. Within its norm isometry group $E_6$, an
automorphism must fix the identity element. This makes the Jordan algebra
particularly natural for $F_4$ #citation[@bib:Chevalley1950, @bib:Jacobson1960,
  @bib:Jacobson1971, @bib:Seligman1960].

#source(272)
The following weight diagram represents this 27-dimensional module. The simple
roots $alpha_1,alpha_2$ are long and $alpha_3,alpha_4$ are short, as in
Bourbaki. There are 24 nonzero weights and a three-dimensional zero-weight
space; one zero-weight line is the fixed identity. Links into the zero-weight
space depend on its chosen basis and are omitted here, as are some such links in
the original diagram.
#figure(
  exceptional-graph("f4-weights.json", zero-space: true, horizontal: true),
  numbering: none,
)
In characteristic zero, for a nonzero root parameter, a long-root unipotent has
six nonzero entries away from the diagonal in the indicated basis. A short-root
unipotent differs from the identity in 11 or 12 positions; its residue is 10.
These counts need not persist in small characteristics.

=== The case $Phi=E_7$ <ss:type-e7>

The minimal module for $G_("sc")(E_7,R)$ has rank 56 and highest weight
$overline(omega)_7$. It is minuscule, self-dual, and symplectic: fix a
nondegenerate invariant alternating form $h$. Every root unipotent with a
nonzero parameter has 12 nonzero entries outside the diagonal. On restriction to
$E_6$, the module decomposes as $1+27+27^*+1$. This suggests a four-linear
invariant which yields the familiar cubic invariant on a 27-dimensional subspace
when one argument is fixed.
#source(273)
#figure(exceptional-graph("e7-weights.json"), numbering: none)

For a field $K$ of characteristic zero, use pairs of alternating $8 times 8$
matrices:
$ V={(x,y):x,y in M(8,K),x^t=-x,y^t=-y}. $
Here “alternating” also requires zero diagonal. This space has dimension
$28+28=56$. For two pairs put
$
  h((x_1,y_1),(x_2,y_2))=
  1/2 (tr(x_1^t y_2)-tr(x_2^t y_1)),
$
and define the quartic
$ F(x,y)=pf(x)+pf(y)-1/4 tr((x y)^2)+1/16 (tr(x y))^2. $
#source(274)
The symbol $pf$ denotes the Pfaffian. Polarization gives a symmetric four-linear
form $f$. Freudenthal's construction identifies $E_7$ with the subgroup of
$Sp(V, h)$ preserving this form #citation[@bib:Freudenthal1953a, @bib:Baily1970,
  @bib:Harris1971, @bib:Springer1981]. When $6$ is invertible, preserving $f$ is
equivalent to preserving $F$:
$ G_("sc")(E_7,K)={g in Sp(V, h): F(g v)=F(v)" for all "v in V}. $
The displayed fractions and polarization are not definitions over arbitrary
rings; small characteristics require an integral construction.#ed-note[
  Such a construction is now available over $ZZ$: an integral four-linear form
  together with an alternating form defines the simply connected $E_7$ group
  scheme, without a characteristic restriction
  #citation[@bib:VavilovLuzgarev2016, Theorem 2, §9]. The extended group scheme
  is also described as the stabilizer of an ideal generated by 133 integral
  quadrics #citation[@bib:VavilovLuzgarev2016, Theorem 1, §§4, 9]. These are
  scheme identifications over $ZZ$, so they apply after base change to any
  commutative ring; the four-linear form need not be symmetric.
]

Cartan announced the characteristic-zero invariant in 1894, but his construction
was erroneous. Freudenthal supplied the first correct construction and later
described it using the exceptional Jordan algebra
#citation[@bib:Freudenthal1954]. Seligman extended the construction to fields of
characteristic different from $2$ and $3$. Brown axiomatised the four-linear
form #citation[@bib:Brown1969], using the $E_6$ construction. The invariant is
closely related to the 56-dimensional exceptional ternary algebra: its elements
are $2 times 2$ matrices with scalar diagonal entries and exceptional Jordan
algebra entries off the diagonal, $56=1+27+27+1$. A ternary product yields a
four-linear form in the same way that a binary product yields a trilinear one
#citation[@bib:Brown1969, @bib:Faulkner1970a, @bib:Faulkner1970b,
  @bib:Faulkner1977, @bib:Ferrar1972, @bib:Meyberg1968].

Aschbacher's alternative construction uses $A_6$ instead of $E_6$
#citation[@bib:Aschbacher1988]. If $U$ is the natural seven-dimensional
$SL_7$-module, then
$ V=U ⊕ Λ^2 U ⊕ Λ^2 U^* ⊕ U^*, quad 56=7+21+21+7. $
Cooperstein gives further details and another identification of the isometry
group #citation[@bib:Cooperstein1988b]. Aschbacher also constructs an invariant
in characteristic $2$, but it is not symmetric. The forms in odd characteristic
and characteristic $2$ thus differ essentially.
#source(275)
The cubic monomials inherited from $E_6$ constitute one Weyl orbit. To make
their contribution invariant under a root subgroup, one must balance it with a
contribution from another orbit. A coefficient $2$ enters this balance,
explaining the difficulty in characteristic $2$.

=== The case $Phi=E_8$ <ss:type-e8>

Here there is no minuscule representation. The smallest representation is the
adjoint module, the Chevalley Lie algebra $L$ of rank 248. The large weight
diagram contains familiar pieces from $E_7$ and $E_6$
#citation[@bib:Mizuno1980]. Relative to $E_7$, its weight spaces have the
pattern $1+56+133+56+1+1$: the adjoint $E_7$ part, two minimal modules, and
three zero or extremal weight lines. This describes the integral weight
decomposition; it should not be read as a semisimple decomposition in every
characteristic.

The first diagram gives the positive-root part with nonzero coefficient of
$alpha_8$. Its 57 nodes are one extremal root and the 56 weights of an $E_7$
module. Dashed arrows indicate links into the remaining adjoint part; a
negative-root counterpart completes this part of the diagram.
#source(276)
#figure(exceptional-graph("e8-adjoint-piece.json"), numbering: none)
The $E_7$ adjoint part in turn contains two contragredient 27-dimensional $E_6$
modules, its 78-dimensional adjoint module, and a zero-weight line:
$133=27+78+27+1$. The next diagram shows the positive-root part outside $E_6$;
its dashed arrows lead into the adjoint $E_6$ part.
#source(277)
#figure(exceptional-graph("e7-adjoint-piece.json"), numbering: none)
Finally, the 36 positive roots of $E_6$ and the six Cartan basis vectors are
shown below. The negative-root part completes the 78-dimensional adjoint module.
Only part of the action on the Cartan basis is drawn: some arrows into and out
of its six-dimensional span are omitted. In particular, the links between
simple-root vectors and Cartan vectors do not display the full action on this
basis.
#source(278)
#figure(
  exceptional-graph("e6-adjoint-piece.json", coroots: true),
  numbering: none,
)

The Lie bracket and an invariant symmetric bilinear form $B$ give the
alternating trilinear invariant
$ f(x,y,z)=B([x,y],z). $
In characteristic zero one can use the Killing form. On the integral $E_8$ Lie
algebra its normalized form is the Killing form divided by $60$; unlike the
Killing form itself, this normalized pairing is unimodular. Indeed, normalize
the Chevalley basis by $[X_alpha,X_(-alpha)]=H_alpha$. Then
$B(X_alpha,X_(-alpha))=1$, the other root-space pairings vanish unless the roots
are opposite, and the Cartan block is the $E_8$ Cartan matrix. The root blocks
have determinant $-1$ and the Cartan matrix has determinant $1$, so the full
pairing is perfect over $ZZ$ and after any base change. The factor $60=2h^∨$,
with $h^∨=30$, relates this form to the Killing form. The four-linear expression
$ q(x,y,z,u)=B([x,y],[z,u]) $
is invariant as well. Freudenthal used these trilinear and four-linear
expressions in characteristic zero #citation[@bib:Freudenthal1953b].#ed-note[
  The original claim that the full linear isometry group of either single form
  is $E_8$ needs correction. A scalar $zeta I$ preserves $f$ when $zeta^3=1$,
  and preserves $q$ when $zeta^4=1$, although it need not preserve the bracket.
  The Killing form also vanishes in characteristics $2$, $3$, and $5$. Keeping
  the nondegenerate normalized pairing $B$ together with $f$ avoids the scalar
  ambiguity: the equation $B([x,y],z)=f(x,y,z)$ reconstructs the bracket
  uniquely. Thus their common stabilizer is the group of Lie algebra
  automorphisms preserving $B$.
]

The present proofs proceed by types because the natural modules are usually much
smaller than the adjoint ones. Frenkel suggested that suitable
infinite-dimensional representations might instead allow a uniform approach.
#source(279)
Even over fields, understanding the geometry of these representations requires
substantial work. Testerman's results identify the maximal subgroups of
exceptional groups which act irreducibly on their minimal modules
#citation[@bib:Testerman1988]\; the reducible case is the difficult one. Much of
Aschbacher's analysis of maximal subgroups of $E_6(K)$ shows by general
arguments that stabilizers of subspaces are not maximal, without determining all
the orbits and stabilizers. The classification of orbits on two-dimensional
subspaces illustrates the amount of work needed for a complete solution
#citation[@bib:Cohen1988a].
