#import "main-defs.typ": *
#import "statements.typ": *
#let sr = math.op("sr")

== The proofs for $A_l$ <sec:proofs-linear>

We discuss different proofs of the structure theorems in the easiest case, the
special linear group. Throughout this section $R$ is commutative and $n ≥ 3$.

=== Linear transvections <ss:linear-transvections>

#source(289) Write $""^n R$ for rows of length $n$, as opposed to the module
$R^n$ of columns. The dual of $V = R^n$ is $V^* = ""^n R$; the pairing sends a
row $v = (v_1, dots, v_n)$ and a column $u = (u_1, dots, u_n)^t$ to
$v u = sum_(i=1)^n v_i u_i$. Let $e_i$ and $f_i$ denote the $i$th column and row
of the identity.

A _linear transvection_ is
$ t_(u v)(ξ) = e + u ξ v, quad v u = 0. $
Its determinant is $1$, so it belongs to $SL(n, R) = G_("sc")(A_(n-1), R)$.
Moreover
$ t_(u v)(ξ)^(-1) = e - u ξ v $
since $(u ξ v)^2 = 0$. #metadata((
  kind: "passage",
)) <passage:linear-transvection-inverse>
Transvections with fixed centre and axis form the root-type subgroup
$ X_(u v) = {t_(u v)(ξ) : ξ ∈ R}. $
A root unipotent is a conjugate of an elementary transvection. Conjugation
preserves transvections:
$ g t_(u v)(ξ) g^(-1) = t_(g u, v g^(-1))(ξ), quad g ∈ GL(n, R). $
Every elementary $t_(i j)(ξ)$ corresponds to $u=e_i$, $v=f_j$. Over a field the
converse holds: every transvection is conjugate to an elementary one. Over
general rings the group $T(n, R)$ generated by all transvections can be strictly
larger than $E(n, R)$.

The crucial feature is additivity. If $v u = v w = 0$, then
$
  t_(u+w, v)(ξ) = e + (u+w) ξ v
  = (e + u ξ v)(e + w ξ v) = t_(u v)(ξ) t_(w v)(ξ).
$
There is an analogous identity in the row argument. In the elementary
independent configuration the two root subgroups correspond to roots at angle
$pi/3$. Thus, for three distinct #source(290) indices $i,j,k$,
$t_(i j)(ξ)t_(i k)(ζ)$ is a transvection, but usually not a root unipotent in
the traditional sense. A necessary condition for it to be conjugate to
$t_(1 2)(θ)$ is that $(ξ,ζ)$ be principal, generated by $θ$. For $n ≥ 4$ the
author states that this is sufficient; in degree three stronger restrictions
than the Bézout property are required. The new proofs use products of two root
unipotents which are not themselves root unipotents.

=== The Whitehead–Vaserstein lemma <ss:whitehead-vaserstein>

A key ingredient in normality proofs is the following elementary fact. Here the
coefficient ring may be any associative ring with identity. Let $I$ be a
two-sided ideal of $R$, $x ∈ M_(r × s)(R)$ and $y ∈ M_(s × r)(I)$. If $e + x y$
is invertible, so is $e + y x$, and#ed-note[
  The inverse on the lower diagonal block is missing in the original. It is
  necessary even in dimension two: without it the determinant need not be one.
  Suslin writes the rectangular identity with the inverse explicitly and
  attributes it to Vaserstein #citation[@bib:Suslin1977, §1, Lemma 1.1]. The
  same identity, with the blocks interchanged, appears in Quillen's notebook,
  entry of 10 January 1995 #citation[@bib:Quillen1995, p. 174].
]
$ mat(e + x y, 0; 0, (e + y x)^(-1)) ∈ E(r+s, R, I). $
<eq:whitehead-vaserstein-block>

The inverse is given by
$ (e + y x)^(-1) = e - y (e + x y)^(-1) x. $
#metadata((kind: "passage")) <passage:jacobson-inverse>

For completeness, set $X=x$, $Y=y$, $A=e+X Y$, $Z=A^(-1)$, and $D=e-Y Z X$. For
rectangular blocks of the appropriate sizes, write
$ U(B)=mat(e, B; 0, e), quad L(C)=mat(e, 0; C, e). $
Since $A Z=Z A=e$, we have $A Z X=X$ and $D Y=Y-Y Z X Y=Y Z$, hence $D Y A=Y$.
Consequently,
$
  U(X)L(Y)U(-Z X)
  =mat(A, X-A Z X; Y, e-Y Z X)=mat(A, 0; Y, D),
$
and therefore
$ U(X)L(Y)U(-Z X)L(-Y A)=mat(A, 0; 0, D). $
<eq:whitehead-four-factorisation>
The equality $D Y=Y Z$ also proves the stated inverse formula: $D(e+Y X)=e$ and
$(e+Y X)D=e$, using respectively $Z A=e$ and $A Z=e$.

To see the relative elementary membership, note that $X-Z X=Z X Y X$, by
$Z A=e$. Regrouping the two adjacent upper unipotents gives
$
  mat(A, 0; 0, D)
  =U(X)L(Y)U(-X)U(X-Z X)L(-Y A).
$
<eq:whitehead-relative-factorisation>
Each $U(B)$ and $L(C)$ is a product of commuting elementary matrices in its
off-diagonal block. Since the entries of $Y$ lie in the two-sided ideal $I$, the
first three factors form the conjugate $U(X)L(Y)U(X)^(-1)$ of an element of
$E(r+s,R,I)$ by an element of $E(r+s,R)$. The remaining factors also belong to
$E(r+s,R,I)$: the entries of $X-Z X=Z X Y X$ and $-Y A$ lie in $I$. Their
product proves the lemma. No commutativity of $R$ was used.

The classical Whitehead lemma has $r=s$ #citation[@bib:Bass1968,
  @bib:Milnor1971]. The rectangular version is attributed to Vaserstein in
Suslin's formulation #citation[@bib:Suslin1977, §1, Lemma 1.1], which cites
#citation[@bib:Vaserstein1969a]\; the original survey also points to
#citation[@bib:Vaserstein1969b, @bib:Vaserstein1976].

We return to commutative coefficient rings. For the normality proofs we need
only a simpler consequence, which has a short direct proof. If $ξ∈I$, $v u=0$,
and one component of $u$ or $v$ vanishes, then $t_(u v)(ξ)∈E(n,R,I)$. Suppose
$v_j=0$, and put $u'=u-u_j e_j$. The matrices
$ a=e+u'f_j, quad b=e+e_j ξ v, quad c=e+u_j e_j ξ v $
belong respectively to $E(n,R)$, $E(n,R,I)$, and $E(n,R,I)$, because each is a
product of elementary matrices in one column or row. Since
$v u'=f_j u'=v e_j=0$, direct multiplication gives
$ [a,b]=e+u'ξ v, quad e+u ξ v=c[a,b]. $
<eq:zero-component-commutator>
The relative group is normal in $E(n,R)$ by definition, so the claim follows. A
zero coordinate of $u$ is treated by the row version of the same calculation.
This proof works over an associative ring with $1$ and a two-sided ideal.

#source(291) A root-theoretic explanation and a recipe for other Chevalley
groups appear in #citation[@bib:Vavilov1988e]\; the idea goes back to
#citation[@bib:Bass1967]. Consider a conjugate $g t_(i j)(ξ)g^(-1)$, where
$ξ∈I$, $1≤i≠j≤n-1$, and $g∈GL(n-1, R)$ is embedded by $g ↦ mat(g, 0; 0, 1)$.
This is the block-embedded conjugate in Vaserstein's proof
#citation[@bib:Vaserstein1981, Lemma 9]. Taking $(i,j)=(1,2)$,
$ t_(1 2)(ξ)=[t_(1 n)(1),t_(n 2)(ξ)], $
and conjugation gives
$
  g t_(1 2)(ξ)g^(-1)
  = [g t_(1 n)(1)g^(-1), g t_(n 2)(ξ)g^(-1)].
$
The two factors are
$ mat(e, g e_1; 0, 1), quad mat(e, 0; ξ f_2 g^(-1), 1). $
More generally, if $v u=0$, direct multiplication gives
$
  mat(e + u ξ v, 0; 0, 1)
  = [mat(e, 0; -v, 1), mat(e, ξ u; 0, 1)].
$
This decomposes a root-type element in a Levi subgroup into root-type elements
of opposite unipotent radicals. The same idea works in other Chevalley groups,
but their commutator formula may have several root factors and require more than
four factors altogether #citation[@bib:Vavilov1988e].

=== Proofs using stability <ss:proofs-stability>

Bass's first proof for broad classes of rings used stability. #source(292)
_Surjective stability_ for $K_1$ asserts that, under conditions on $R$ depending
on an embedding $Delta ⊂ Phi$, the map $K_1(Delta,R) → K_1(Phi,R)$ is
surjective, or equivalently
$ G(Phi,R)=E(Phi,R)G(Delta,R). $
The extensive literature includes #citation[@bib:Bass1964, @bib:Bass1968,
  @bib:Bass1973a, @bib:Bass1967, @bib:Vaserstein1969a, @bib:Vaserstein1969b,
  @bib:Vaserstein1970, @bib:Stein1971b, @bib:Stein1973, @bib:Stein1983,
  @bib:Stein1978, @bib:Suslin1981a, @bib:Suslin1977, @bib:Suslin1985,
  @bib:Tulenbaev1981, @bib:Plotkin1984b, @bib:Plotkin1985a, @bib:Plotkin1985b,
  @bib:Plotkin1989, @bib:Plotkin1991]. Plotkin gave a detailed account at the
same conference.

For linear groups, $n ≥ sr(R)+1$ implies
$ GL(n, R)=E(n,R)GL(n-1, R). $
This goes back to Bass #citation[@bib:Bass1964, @bib:Bass1967]. Let
$(a_1,dots,a_n)$ be the last row of $g ∈ GL(n, R)$. With $n=l+1$, stable rank
gives $b_1,dots,b_l$ such that $(a_1+a_n b_1,dots,a_l+a_n b_l)$ is unimodular.
Set
$ x=t_(n 1)(b_1) dots t_(n l)(b_l). $
The last row of $g x$ is $(a'_1,dots,a'_l,a_n)$ with $a'_i=a_i+a_n b_i$. Choose
$c_i$ with
#source(293)
$
  a_n-1=sum_(i=1)^l a'_i c_i, quad
  y=t_(1 n)(-c_1) dots t_(l n)(-c_l).
$
Then $z=g x y$ has lower right entry $1$. Chevalley–Matsumoto decomposition
places $z$, hence $g$, in $GL(n-1, R)E(n,R)$.

The @ss:whitehead-vaserstein[Whitehead–Vaserstein lemma] shows that $GL(n-1, R)$
normalises $E(n,R,I)$ #citation[@bib:Vaserstein1981, Lemma 9], and $E(n,R)$ does
so by definition. Thus the relative group is normal for $n ≥ sr(R)+1$.
Commutativity was not used in this argument.

The method can be imitated for other root systems, but a component can usually
be added to only some of the others. One must work with shorter, not necessarily
unimodular rows, or use the relations among components. Stein's first approach
leads to absolute stable rank. Vaserstein introduced conditions involving
quadratic or Hermitian equations in classical cases
#citation[@bib:Vaserstein1970]. At the time of this survey, Plotkin had
formulated a plausible general conjecture.

=== Suslin's proof of Suslin's theorem <ss:suslin-proof>

Suslin's original proof #citation[@bib:Suslin1977, §1, Lemma 1.3 and Corollary
  1.4] decomposes solutions of a homogeneous linear equation into two-term
solutions. Let $v=(v_1,dots,v_n)$ be a unimodular row, and consider
$sum_(i=1)^n v_i u_i=0$. The vectors $v_j e_i-v_i e_j$ are obvious solutions.
Every solution is a linear combination of them. #source(294) Indeed choose $w$
with $sum_i v_i w_i=1$. Direct calculation gives
$ u=sum_(1≤i<j≤n) (w_j u_i-w_i u_j)(v_j e_i-v_i e_j). $
<eq:suslin-syzygy-decomposition>
#metadata((kind: "passage")) <passage:suslin-syzygies>
Call each summand $w_(i j)$; it has at most two nonzero components.

For $v u=0$, $v$ unimodular and $ξ ∈ I$, additivity yields
$ t_(u v)(ξ)=product_(i<j)t_(w_(i j),v)(ξ). $
Each $w_(i j)$ has a zero component since $n ≥3$, so every factor lies in
$E(n,R,I)$ by the @ss:whitehead-vaserstein[Whitehead–Vaserstein lemma]. Their
product does also. Now
$ g t_(r s)(ξ)g^(-1)=t_(g e_r,f_s g^(-1))(ξ), $
and every row of an invertible matrix is unimodular. Thus every conjugate of a
relative elementary generator lies in the relative elementary group, completing
the normality proof.

For other Chevalley groups, apart from the symplectic case, the columns and rows
satisfy quadratic relations. Applying this idea would require solving systems of
linear and quadratic equations over an arbitrary ring. Although possible in the
needed cases, the formulae are awkward. Remarkably, this can be avoided, as we
now explain.

=== Stepanov's proof of Suslin's theorem <ss:stepanov-proof>

#source(295) The idea is to decompose the small element before conjugating it.
For $t_(r s)(ξ)$, $ξ ∈ I$, and $g ∈ GL(n, R)$, seek transvections $x_i$ of level
$I$ such that
$
  t_(r s)(ξ)=product_(i=1)^n x_i, quad
  x_i g^(-1)e_i=g^(-1)e_i.
$
Write $x_i=e+e_1 r_i$ with the row $r_i$ of level $I$. Then
$g x_i g^(-1)=e+(g e_1)(r_i g^(-1))$. Its centre $g e_1$ is unimodular, with
left inverse $f_1g^(-1)$. If it fixes $e_i$, then $(g e_1)(r_i g^(-1))_i=0$;
multiplication by that left inverse gives $(r_i g^(-1))_i=0$. The zero-component
calculation therefore makes the conjugate relative elementary. Their product is
the desired conjugate.

Take $(r,s)=(1,2)$, and write $g^(-1)=(g'_(i j))$. For an auxiliary index $3$,
seek $x_i=t_(1 2)(a_i)t_(1 3)(b_i)$. The $i$th column is fixed when
$a_i g'_(2 i)+b_i g'_(3 i)=0$. Commutativity suggests $a_i=g'_(3 i)$,
$b_i=-g'_(2 i)$, and a common multiplier imposes level $I$. To obtain the
required product, #source(296) use the third column of $g$ and set
$
  x_i=t_(1 2)(g_(i 3) ξ g'_(3 i))
  t_(1 3)(-g_(i 3) ξ g'_(2 i)).
$
<eq:stepanov-linear-factors>
Then $sum_i g_(i 3)g'_(3 i)=1$ and $sum_i g_(i 3)g'_(2 i)=0$, so the product is
$t_(1 2)(ξ)$ and the fixed-column condition holds. This completes the proof.

This proof combines only elementary calculations and calculations with one
column. Stepanov's thesis gives variants and generalisations, including proofs
in the stable range #citation[@bib:Stepanov1987]. Both kinds of calculation are
available in arbitrary Chevalley groups; this is the guiding idea.

=== The Borewicz–Vavilov proof <ss:borewicz-vavilov-proof>


Stepanov's trick clarifies an idea already implicit in the simplified proof of
#citation[@bib:Borevich1985]. It suffices to find a noncentral element of an
elementary-normalised subgroup $F$ in a proper parabolic, for instance #source(
  297,
)
$ z=mat(ξ, u; 0, c) ∈ F, quad ξ ∈ R^times, quad c ∈ GL(n-1, R). $
Take noncentral $g=(g_(i j))∈F$, inverse $(g'_(i j))$, and put
$
  x_r=t_(1 2)(g'_(3 r))t_(1 3)(-g'_(2 r)), quad
  z_r=[g,x_r]=g x_r g^(-1)x_r^(-1).
$
The conjugate fixes $e_r$; its rank-one expression is
$
  z_r=(e+sum_(i,j)g_(i 1)
    (g'_(3 r)g'_(2 j)-g'_(2 r)g'_(3 j))e_(i j))x_r^(-1).
$
The first column of $z_1$ is $e_1$. If $z_1$ is noncentral, use it. If central,
its upper left entry forces $z_1=e$, whence
$
  g_(i 1)(g'_(3 1)g'_(2 j)-g'_(2 1)g'_(3 j))=0
  quad (2≤i≤n).
$
Consequently all $z_r$ preserve the first coordinate line. If any is noncentral,
use it. If all are scalar, the analogous equations give
$ g_(i 1)(g'_(3 r)g'_(2 j)-g'_(2 r)g'_(3 j))=0 $
for $i≥2$ and $j≠i$. They also hold for $j=i$: trivially if $j=r$, otherwise by
antisymmetry in $j,r$. The $2×2$ minors of the second and third rows of $g^(-1)$
generate the unit ideal, by Laplace expansion. Thus $g_(i 1)=0$ for $i≥2$, and
$g$ itself lies in the required parabolic. Since it is noncentral, the proof is
complete.

The extra factor $x_r^(-1)$ obscures column symmetry, but #source(298) all
calculations again involve elementary operations and one column at a time.

=== Localisation and patching proofs <ss:localisation-patching>

Another proof uses the Quillen–Suslin localisation principle. Suslin called the
following statement Quillen's theorem because of its similarity to Quillen's
solution of Serre's problem #citation[@bib:Suslin1977, §3, Theorem 3.1;
  @bib:Quillen1976]\; Suslin's solution used the same idea
#citation[@bib:Suslin1976].

#theorem(numbered: false)[
  Let $n≥3$, and let $g∈GL(n, R[X], X R[X])$, so $g(0)=e$. Then $g∈E(n,R[X])$ if
  and only if its image belongs to $E(n,R_m[X])$ for every maximal ideal $m$ of
  $R$.
] <th:quillen-suslin-local-global>

For $a∈R$, write $R_a=R[a^(-1)]$. If $a$ is not a zero divisor, the map $R→R_a$
is injective. Let $I(g)$ be the set of $a$ for which the image of $g$ is
elementary over $R_a[X]$. The patching argument shows that $I(g)$ is an ideal.
The hypothesis makes it lie in no maximal ideal, hence $I(g)=R$ and $1∈I(g)$.

Suslin, Kopeiko, Abe, Vorst, Costa and others developed polynomial versions for
Chevalley groups #citation[@bib:Suslin1982, @bib:Kopeiko1978, @bib:Abe1983,
  @bib:Vorst1981, @bib:Costa1988]. Vaserstein applied the idea to structure
theorems for commutative, almost commutative, and more general rings with
suitable local stable rank bounds #citation[@bib:Vaserstein1981, Theorem 4;
  Proposition 12; Theorem 13 and Corollary 14]. Taddei used it for normality,
#citation[@bib:Taddei1985, @bib:Taddei1986] and Vaserstein and Abe for normal
structure #citation[@bib:Vaserstein1986b, @bib:Abe1989a,
  @bib:Abe1989b]. Later work covered broad classes of nonsplit groups
#citation[@bib:Vaserstein1988, @bib:Vaserstein1989]. #ed-note[
  Stepanov's dissertation gives the dilation lemma, the polynomial local-global
  principle, and its application to normality #citation[@bib:Stepanov2014,
    §§2.4–2.6]. Its Chapter III introduces a universal congruence element and an
  enlarged elementary group, then obtains uniform commutator bounds and relative
  and multiple commutator formulae #citation[@bib:Stepanov2014, §§3.1–3.6]. The
  published treatment is _Structure of Chevalley groups over rings via universal
  localization_ #citation[@bib:Stepanov2016]. These are later developments of
  the generic-element method.
]

=== Winnie-the-Pooh comments <ss:proof-comparison>

The major Taoist thinker Winnie-the-Pooh observes that different proofs prove
different things; otherwise they would be the same proof. #source(299) The four
arguments above indeed differ both in scope and conclusion.

The @ss:whitehead-vaserstein[Whitehead–Vaserstein lemma] gives
$T(n,R)≤E(n+1,R)$. _Injective stability_ means that, under appropriate
conditions, an embedding $Delta⊂Phi$ induces an injection on $K_1$, equivalently
$ E(Delta,R)=E(Phi,R)∩G(Delta,R). $
For linear groups the Bass–Vaserstein theorem #citation[@bib:Bass1964,
  @bib:Bass1968, @bib:Bass1967, @bib:Vavilov1984, @bib:Vavilov1986,
  @bib:Suslin1981b] gives
$ E(n,R)=E(n+1,R)∩GL(n, R), quad n≥sr(R)+1. $
Thus $T(n,R)=E(n,R)$ in this range.

Let $E'(n,R)$ be the normal closure of $E(n,R)$ in $GL(n, R)$, and $E''(n,R)$
the group generated by transvections with a unimodular row parameter.
Conjugation shows $E'≤E''$, since rows of invertible matrices are unimodular.
The reverse inclusion is not immediate. Suslin proves $E''=E$ over commutative
rings for $n≥3$, whereas Stepanov proves $E'=E$, precisely normality. A weaker
conclusion admits a simpler proof. In length two every unimodular row over a
commutative ring extends to an invertible matrix, #citation[@bib:Bass1968] so
$E'(2,R)=E''(2,R)$.

Localisation proves a different statement: under the polynomial normalisation
hypothesis, local elementary membership implies global elementary membership. To
apply it to a transvection or a conjugate, one introduces a polynomial parameter
so that the matrix becomes the identity at zero. It is this extra hypothesis
that makes patching possible; local elementary membership of a constant matrix
alone does not imply global membership.
