#import "main-defs.typ": *
#import "statements.typ": *

== The proofs for $B_l$ and $D_l$ <sec:proofs-orthogonal>

#source(300) The orthogonal case resembles the linear one, but the quadratic
form places additional restrictions on the parameters. We first describe the
relevant small transformations and then explain how the column-stabilising
argument adapts to them.

=== ESD-transvections <ss:esd-transvections>

Let $V=R^n$ carry the standard split symmetric form. In the formulas containing
$1/2$, assume $2∈R^times$. If $u$ is isotropic and $(u,v)=0$, the
_Eichler–Siegel–Dickson transvection_ is
$
  T_(u,v)(ξ)x=x-ξ(u,x)v+ξ(v,x)u
  -1/2 ξ^2(v,v)(u,x)u.
$
This preserves the quadratic form. If $v$ is also isotropic, the quadratic term
vanishes; these are the transformations of long root type. The distinction
matters in odd dimension, where the short root elements require the full ESD
formula.

Direct substitution gives
$
  T_(u,v)(ξ)T_(u,v)(ζ)=T_(u,v)(ξ+ζ), quad
  T_(u,v)(ξ)^(-1)=T_(u,v)(-ξ).
$
For an isometry $g$,
$ g T_(u,v)(ξ)g^(-1)=T_(g u,g v)(ξ). $
#metadata((kind: "passage")) <passage:esd-conjugation>
Consequently the group generated by all ESD-transvections is normal in the
orthogonal isometry group. This _Eichler subgroup_ coincides with the elementary
orthogonal group over a field and in the stable setting, but may be larger over
a general ring. For a similitude of multiplier $μ$, the parameter on the right
becomes $ξ/μ$. #source(301) Elementary orthogonal transvections arise by taking
$u=e_i$, $v=e_(-j)$, for the admissible pairs of indices.

For a column $u$, put $tilde(u)=(F u)^t$, where $F$ is the matrix of the
symmetric form. Thus $tilde(u)_i=u_(-i)$ for $i≠0$, and $tilde(u)_0=2u_0$ in odd
dimension. Then $(u,v)=tilde(v)u$, and
$
  T_(u,v)(ξ)=e+u ξ tilde(v)-v ξ tilde(u)
  -1/2 u ξ^2(tilde(v)v)tilde(u).
$
For isotropic orthogonal $u,v$ this reduces to
$ T_(u,v)(ξ)=e+u ξ tilde(v)-v ξ tilde(u). $
If $u$ is isotropic and orthogonal to $v,w$, the general ESD formula also yields
$ T_(u,v)(ξ)T_(u,w)(ζ)=T_(u,ξ v+ζ w)(1). $

=== Products in an isotropic three-space <ss:orthogonal-column-stabiliser>


For the displayed three-direction construction assume $l≥3$. Suppose $u,v,w$
span a totally isotropic submodule: the quadratic form vanishes on every vector
of their span. The products
$ T_(u,v)(η)T_(u,w)(ζ)T_(v,w)(θ) $
have square-zero displacement and are particularly useful for fixing columns. In
a Witt basis containing $u=e_1$, $v=e_2$, $w=e_3$, their matrix on the
coordinates $1,2,3,-3,-2,-1$ is#ed-note[
  The original identifies this product with $T_(x,y)(1)$ using $x=u+v+w$ and a
  particular linear expression for $y$. That expression does not give the stated
  product: already $η=1$, $ζ=θ=0$ yields different matrices over $QQ$. We retain
  the product and its direct matrix calculation.
]
#source(302)
$
  mat(
    1, 0, 0, ζ, η, 0;
    0, 1, 0, θ, 0, -η;
    0, 0, 1, 0, -θ, -ζ;
    0, 0, 0, 1, 0, 0;
    0, 0, 0, 0, 1, 0;
    0, 0, 0, 0, 0, 1
  ).
$
<eq:orthogonal-three-space>

Thus the product
$ t=T_(1,-2)(η)T_(1,-3)(ζ)T_(2,-3)(θ) $
fixes a column $a$ provided
$
  ζ a_(-3)+η a_(-2)=0, quad
  θ a_(-3)-η a_(-1)=0, quad
  -θ a_(-2)-ζ a_(-1)=0.
$
The choice
$ η=-a_(-3), quad ζ=a_(-2), quad θ=-a_(-1) $
satisfies all three equations over any commutative ring. Multiplying these three
parameters by a common scalar preserves this property. The construction is the
orthogonal counterpart of Stepanov's linear column-stabiliser: a small commuting
family replaces the two transvections used there.

=== Normality <ss:orthogonal-normality>

For a conjugating matrix $g$, write $g^(-1)=(g'_(i j))$. The following
decomposition supplies a product of column-stabilisers, the geometric ingredient
of the method. Its matrix identities are independent of the further
elementary-group arguments.

#source(303) For $T_(1,-2)(ξ)$, take
$
  x_i=T_(1,-2)(g_(i,-3)ξ g'_(-3,i))
  T_(1,-3)(-g_(i,-3)ξ g'_(-2,i))
  T_(2,-3)(g_(i,-3)ξ g'_(-1,i)).
$
<eq:orthogonal-stepanov-factors>
The displayed fixed-column equations show that $x_i$ fixes $g^(-1)e_i$. The
three root subgroups commute, and the identities
$
  sum_i g'_(-3,i)g_(i,-3)=1, quad
  sum_i g'_(-2,i)g_(i,-3)=sum_i g'_(-1,i)g_(i,-3)=0
$
give $product_i x_i=T_(1,-2)(ξ)$. If $ξ∈I$, all parameters lie in $I$.
#metadata((kind: "passage")) <passage:orthogonal-factor-product>

Fixing a column does not alone imply that the conjugate is elementary: a proper
parabolic still contains its Levi factor. To complete a geometric proof one
needs an additional Whitehead-type lemma for the particular unipotent shape. For
absolute normality we use Taddei's uniform theorem, introduced in
§@ss:commutator-formulae #citation[@bib:Taddei1985, @bib:Taddei1986]. Relative
normality follows from the full split-pullback argument in
@passage:relative-normality-pullback[the proof for $E_6$]. This route applies to
both split series $B_l,D_l$ of rank at least two, without a stable-rank
condition. The displayed ESD formulas still use $2∈R^times$; the uniform
normality theorem does not.

The geometric approach to normal structure seeks a noncentral element fixing a
basis vector, then reduces to a proper parabolic. For $D_l$, the displayed
calculation takes place inside an $A_3$ subsystem; its form explains the
generalisation to exceptional groups #citation[@bib:Vavilov1988b,
  @bib:Vavilov1990b, @bib:Vavilov1987].

=== Further orthogonal settings <ss:orthogonal-further>

#source(304) The same methods are useful for subgroups of $GL(n, R)$ normalised
by $EO(n, R)$. Their description involves more than one ideal, since the ambient
linear group contains transformations that do not preserve the quadratic form.
This belongs to the general theory of subgroups normalised by smaller elementary
groups, discussed again in §@sec:concluding-remarks.

The split form can also be replaced by a form containing a large enough
hyperbolic summand. Three independent mutually orthogonal isotropic directions
suffice for the displayed construction. In favourable settings, localisation
lowers the needed global Witt-index assumption. Orthogonal groups over rings,
quadratic modules with involution, and relative groups with form parameters must
be treated with their own level data rather than an ideal alone.#ed-note[
  For the definitions of form parameters and form ideals and the corresponding
  relative elementary groups, see #citation[@bib:Hahn1989b, §§5.1C, 5.2D, and
    5.3D]. These distinctions are essential when extending the split orthogonal
  argument to unitary groups.
] Later work supplies a general formulation for isotropic reductive groups. If,
after localisation at every maximal ideal, each irreducible component of the
relative root system has rank at least two, the elementary subgroup attached to
a strictly proper parabolic is independent of that parabolic and normal. A
parabolic is _strictly proper_ if it meets every nontrivial semisimple normal
component properly.#ed-note[
  The rank condition in Petrov and Stavrova's theorem applies to every relative
  component over every local ring; the existence of one split torus of rank two
  does not suffice #citation[@bib:PetrovStavrova2009, Theorem 1].
]
