#import "main-defs.typ": *
#import "statements.typ": *

== The proofs for $C_l$ <sec:proofs-symplectic>

#source(305) We outline the symplectic normality argument. The normal-structure
proof follows the same pattern. The coincidence $B_2=C_2$ permits the transfer
of rank-two calculations to the odd orthogonal case. The geometry of long root
subgroups is less rich here: two distinct long roots are orthogonal or opposite.
This makes column-stabilising decompositions more delicate than in the linear
and even orthogonal cases.

=== Symplectic transvections <ss:symplectic-transvections>

Let $V=R^(2ell)$ carry the standard nondegenerate alternating form with matrix
$F$, and let $(e_i)$ be its Witt basis. For $u∈V$ and $ξ∈R$, define
$ T_u (ξ)x=x+ξ(u,x)u. $
For orthogonal $u,v$, define
$ T_(u,v)(ξ)x=x+ξ(u,x)v+ξ(v,x)u. $
Both transformations preserve the alternating form. The first are the symplectic
transvections of long root type; the second, when $u,v$ are independent, are
transformations of short root type. If $2$ is invertible,
$T_u (ξ)=T_(u,u)(ξ/2)$.

Conjugation by a symplectic matrix gives
$
  g T_u (ξ)g^(-1)=T_(g u)(ξ), quad
  g T_(u,v)(ξ)g^(-1)=T_(g u,g v)(ξ).
$
The elementary root elements are the corresponding transformations with standard
basis vectors. Put $tilde(u)=u^t F=-(F u)^t$; with the chosen ordering of
indices,
#source(306)
$ tilde(u)=(-u_(-1),dots,-u_(-l),u_l,dots,u_1). $
Then $(u,v)=tilde(u)v$, and the matrices are
$
  T_u (ξ)=e+u ξ tilde(u), quad
  T_(u,v)(ξ)=e+u ξ tilde(v)+v ξ tilde(u).
$
<eq:symplectic-transvections>

=== Stabilising a column with long root elements <ss:symplectic-long-stabiliser>


Let $(u,v)=0$. A direct multiplication gives
$ T_(u,v)(η θ)T_u (η^2)T_v (θ^2)=T_(η u+θ v)(1). $
<eq:symplectic-long-product>
Taking $u=e_1$, $v=e_2$ gives, on the coordinates $1,2,-2,-1$,
$
  t=T_(1,-2)(η θ)T_(1,-1)(η^2)T_(2,-2)(θ^2)
  =mat(
    1, 0, η θ, η^2; 0, 1, θ^2, η θ;
    0, 0, 1, 0; 0, 0, 0, 1
  ).
$
To fix a column $a$, choose $η=a_(-2)$ and $θ=-a_(-1)$. The two potentially
changed coordinates then remain unchanged. This quadratic choice illustrates
both the usefulness and the limitation of the long root geometry.

#source(307) For $g^(-1)=(g'_(i j))$, the factors
$
  x_i=T_(1,-2)(-g'_(-1,i)g'_(-2,i))
  T_(1,-1)((g'_(-2,i))^2)
  T_(2,-2)((g'_(-1,i))^2)
$
fix the $i$th column of $g^(-1)$. Their parameters may all be multiplied by a
common scalar $ξ$; if $ξ∈I$, they have level $I$. After conjugation the fixed
column brings the factors within reach of an elementary parabolic calculation.
Unlike the linear case, however, the squares cannot simply be summed using
$g^(-1)g=e$ to recover one prescribed root element. The approach therefore leads
to a more elaborate study of the group generated by these stabilisers and of its
level data. This is closely related to the net-subgroup methods in
#citation[@bib:Vavilov1988b, @bib:Vavilov1990b,
  @bib:Vavilov1987].

=== Short root elements and two columns <ss:symplectic-short-stabiliser>


Short root elements provide a different route. Products involving one short-root
direction and the associated long-root direction can be arranged to fix two
columns at once. If $2∈R^times$, the following parametrisation is especially
convenient. In rank two,
#source(308)
$
  t=T_(1,2)(ζ)T_(1,-2)(η)T_(1,-1)(2θ-ζ η)
  =mat(1, ζ, η, 2θ; 0, 1, 0, η; 0, 0, 1, -ζ; 0, 0, 0, 1).
$
<eq:symplectic-short-product>
The associated linear transvection
$ z=t_(1,2)(ζ)t_(1,3)(η)t_(1,4)(θ) $
fixes two columns $u,v$ when
$
  ζ u_2+η u_3+θ u_4=0, quad
  ζ v_2+η v_3+θ v_4=0.
$
An elementary solution is
$
  ζ=u_3v_4-u_4v_3, quad
  η=u_4v_2-u_2v_4, quad
  θ=u_2v_3-u_3v_2.
$
<eq:symplectic-minor-syzygy>
These are the signed $2×2$ minors of the last three rows. A common scalar
multiplier is again allowed. The two equations follow by expanding determinants
with repeated columns, so no division or field hypothesis is involved.

#source(309) Factor the matrix $t$ as
$
  t=mat(1, 0, 0, θ; 0, 1, 0, η; 0, 0, 1, -ζ; 0, 0, 0, 1)
  mat(1, ζ, η, θ; 0, 1, 0, 0; 0, 0, 1, 0; 0, 0, 0, 1).
$
<eq:symplectic-short-factorisation>
If the second factor fixes columns $j,h$ of $g^(-1)$, preservation of the
symplectic form relates this to the rows $-j,-h$ of $g$. For $j≠-h$, the
relevant conjugate is reduced to a proper parabolic. For $j=-h$, a small
symplectic transvection calculation is needed instead. Kopeiko's proof provides
precisely this latter calculation #citation[@bib:Kopeiko1978].

To recover an elementary root element from the resulting factors, one combines
these minors with the corresponding minors of $g$; the Cauchy–Binet identity
supplies the required sums. In higher rank the same idea uses larger minors.
Care is needed with the central parameter: in the displayed short-root product
its value is $2θ-ζ η$, not an independent linear function of the minors.

This explains the additional complexity of the original representation-based
proof. Absolute normality for $C_l$, $l≥2$, follows from Taddei’s uniform
theorem without a restriction on $2$ #citation[@bib:Taddei1985,
  @bib:Taddei1986]. The split-pullback argument in
@passage:relative-normality-pullback[the proof for $E_6$]
then proves relative normality over every commutative ring. The relative
commutator formula also has a uniform proof in the later relative commutator
calculus, under the stated hypotheses on the coefficient ring.#ed-note[
  The mixed commutator theorem of Hazrat, Vavilov, and Zhang
  #citation[@bib:HazratVavilovZhang2013, Theorem 1] has the following
  hypotheses: type $C_2$ requires that the ring have no residue field of two
  elements; in type $C_l$ each $c∈R$ lies in $c^2R+2c R$. The latter condition
  holds in particular when $2$ is invertible. These hypotheses must accompany
  the uniform relative formula; the theorem is not a normal-subgroup
  classification.
]
